/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.sidebar;

import it.vs30.myeditor.FineTuning;
import it.vs30.myeditor.JSezioneView;
import it.vs30.myeditor.jTavolozzaDlg;
import java.awt.Color;
import org.myorg.myapi.APIObject;
import org.myorg.myapi.Indagine;
import org.myorg.myviewer.MyViewerTopComponent;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 *
 * @author simone
 */
public class profileTools extends javax.swing.JPanel {

    private APIObject obj;
    public double[] tV1;
    double spaz;
    JSezioneView sV;
    double[] tV2;
    private jTavolozzaDlg tavo_dlg;
    public double[] V2;
    public double[] V3;
    Indagine proj;
    
    
    /**
     * Creates new form profileTools
     */
    public profileTools() {
        initComponents();
    }
   
    
    void setAPIObject(APIObject active) {
        this.obj = active;
        setProj(obj.proj);
    }
    
    public void setSezView(JSezioneView sv){
        sV = sv;
        if (sV.isProporz()) {
            jProportionalProfileButton.setText("Maximize profile");
        } else {
            jProportionalProfileButton.setText("Proportional profile");
        }
        
    }
    
    public void setProj(Indagine prj) {
        this.proj = prj;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPhantomingTvTg = new javax.swing.JButton();
        jProportionalProfileButton = new javax.swing.JButton();
        jWhiteBkgButton = new javax.swing.JButton();
        jSetPalette = new javax.swing.JButton();
        jExportImage = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridLayout(0, 1));

        org.openide.awt.Mnemonics.setLocalizedText(jPhantomingTvTg, org.openide.util.NbBundle.getMessage(profileTools.class, "profileTools.jPhantomingTvTg.text")); // NOI18N
        jPhantomingTvTg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhantomingTvTgActionPerformed(evt);
            }
        });
        add(jPhantomingTvTg);

        org.openide.awt.Mnemonics.setLocalizedText(jProportionalProfileButton, org.openide.util.NbBundle.getMessage(profileTools.class, "profileTools.jProportionalProfileButton.text")); // NOI18N
        jProportionalProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProportionalProfileButtonActionPerformed(evt);
            }
        });
        add(jProportionalProfileButton);

        org.openide.awt.Mnemonics.setLocalizedText(jWhiteBkgButton, org.openide.util.NbBundle.getMessage(profileTools.class, "profileTools.jWhiteBkgButton.text")); // NOI18N
        jWhiteBkgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWhiteBkgButtonActionPerformed(evt);
            }
        });
        add(jWhiteBkgButton);

        org.openide.awt.Mnemonics.setLocalizedText(jSetPalette, org.openide.util.NbBundle.getMessage(profileTools.class, "profileTools.jSetPalette.text")); // NOI18N
        add(jSetPalette);

        org.openide.awt.Mnemonics.setLocalizedText(jExportImage, org.openide.util.NbBundle.getMessage(profileTools.class, "profileTools.jExportImage.text")); // NOI18N
        jExportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExportImageActionPerformed(evt);
            }
        });
        add(jExportImage);
    }// </editor-fold>//GEN-END:initComponents

    private void jProportionalProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProportionalProfileButtonActionPerformed
        // TODO add your handling code here:
        sV.setProporz( !sV.isProporz() );
        
        if (sV.isProporz()) {
            jProportionalProfileButton.setText("Maximize profile");
        } else {
            jProportionalProfileButton.setText("Proportional profile");
        }
        
        sV.invalidate();
        sV.repaint();
        
        
    }//GEN-LAST:event_jProportionalProfileButtonActionPerformed

    private void jWhiteBkgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWhiteBkgButtonActionPerformed
        sV.setBgWhite ( !sV.isBgWhite() );

        if (sV.isBgWhite()) {
            sV.setBackground(Color.WHITE);
        } else {
            sV.setBackground(Color.BLACK);
        }

        this.setVisible(false);
       // sV.obj.is_white = sV.isWhite;
       sV.invalidate();
       sV.repaint();

        TopComponent tc = WindowManager.getDefault().findTopComponent("MyViewerTopComponent");
        Lookup tcLookup = tc.getLookup();

        ((MyViewerTopComponent) tc).gmview.is_white = sV.isBgWhite();
        ((MyViewerTopComponent) tc).gmview.invalidate();
        ((MyViewerTopComponent) tc).gmview.repaint();


// TODO add your handling code here:
    }//GEN-LAST:event_jWhiteBkgButtonActionPerformed

    private void jExportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExportImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExportImageActionPerformed

    private void jPhantomingTvTgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhantomingTvTgActionPerformed
        // TODO add your handling code here:
        FineTuning ft=new FineTuning(obj.proj);
        ft.setProj(this.proj);
        //this.setVisible(false);
        ft.setParentDialog(this.sV);
        ft.setModal(true);
        ft.setVisible(true);
        
    }//GEN-LAST:event_jPhantomingTvTgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExportImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPhantomingTvTg;
    private javax.swing.JButton jProportionalProfileButton;
    private javax.swing.JButton jSetPalette;
    private javax.swing.JButton jWhiteBkgButton;
    // End of variables declaration//GEN-END:variables
}
