/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.sidebar;

import java.util.Collection;
import org.myorg.myapi.APIObject;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.InstanceContent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//it.vs30.sidebar//sideTools_//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "sideTools_TopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "it.vs30.sidebar.sideTools_TopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_sideTools_Action",
        preferredID = "sideTools_TopComponent")
@Messages({
    "CTL_sideTools_Action=sideTools_",
    "CTL_sideTools_TopComponent=sideTools_ Window",
    "HINT_sideTools_TopComponent=This is a sideTools_ window"
})
public final class sideTools_TopComponent extends TopComponent  implements LookupListener  {
    private APIObject active;
    private final InstanceContent content = new InstanceContent();
    private Lookup.Result<APIObject> result;

    public sideTools_TopComponent() {
        initComponents();
        setName(Bundle.CTL_sideTools_TopComponent());
        setToolTipText(Bundle.HINT_sideTools_TopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);
        
        if (getLookup().lookup(sideTools_TopComponent.class) == null) {
            content.add(this);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(200, 130));
        setPreferredSize(new java.awt.Dimension(300, 200));
        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(sideTools_TopComponent.class, "sideTools_TopComponent.jLabel1.text")); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
  

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    @Override
    public void componentOpened() {
        result = Utilities.actionsGlobalContext().lookupResult(APIObject.class);
        result.addLookupListener (this);
      //  txt.setAPIObject();
    }
    
    @Override
    public void componentClosed() {
        result.removeLookupListener (this);
        result = null;
    }
    
    @Override
    public void resultChanged(LookupEvent lookupEvent) {
        Lookup.Result r = (Lookup.Result) lookupEvent.getSource();
        Collection c = r.allInstances();
        if (!c.isEmpty()) {
           
                APIObject o = (APIObject) c.iterator().next();
                active=o;
                jLabel1.setText (" "+o.selected_Tab);
//                setTabSelected(o.selected_Tab);
                //txt.setAPIObject(active);
               // jLabel2.setText (o.getDate().toString());
           
        } else {
           // jLabel1.setText("[no selection]");
           // jLabel2.setText ("");
        }
    }
    
    public void setAPIObject(APIObject obj){
        txt.setAPIObject(obj);
        prfDlg.setAPIObject(obj);
    }
    
    public void setTabSelected(int selectedIndex) {
        jLabel1.setText(""+selectedIndex);//To change body of generated methods, choose Tools | Templates.
        this.removeAll();
        this.add(jLabel1);
        if(selectedIndex==1){
            //this.remove(jLabel1);
            this.add(txt);
            this.updateUI();
        }
        else{
            try{
               this.remove(txt);
               this.updateUI();
            }
            catch(Exception ex){
                
            }
        }
        if(selectedIndex==0){
            //this.remove(jLabel1);
            if(jtr_dlg!=null){
                this.add(jtr_dlg);
            jtr_dlg.setSelectButtonStatus( jtr_dlg.getTraceView().getSelectionMode() );
            }
            
            this.updateUI();
        }
        else{
            try{
               this.remove(jtr_dlg);
               this.updateUI();
            }
            catch(Exception ex){
                
            }
        }
        if(selectedIndex==2){
            //this.remove(jLabel1);
            if(prfDlg!=null){
                this.add(prfDlg);
                //this.add(jtr_dlg);
                //jtr_dlg.setSelectButtonStatus( jtr_dlg.getTraceView().getSelectionMode() );
            }
            
            this.updateUI();
        }
        else{
            try{
               this.remove(prfDlg);
               this.updateUI();
            }
            catch(Exception ex){
                
            }
        }
        
    }
    public tx_tool txt=new tx_tool();
    public trace_tools jtr_dlg=new trace_tools();
    public profileTools prfDlg=new profileTools();
    
}
