/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.sidebar;

import java.awt.Color;
import it.vs30.myeditor.TraceView;
import it.vs30.smartRefract.utils.ZoomTraceUtil;
import it.vs30.welcome.welcomeTopComponent;
import javax.swing.SwingConstants;
import org.myorg.myapi.FirstBrakeList;
//import org.myorg.myviewer.MyViewerTopComponent;

import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;


/**
 *
 * @author PC
 */
public class trace_tools extends javax.swing.JPanel {

    /**
     * Creates new form trace_tools
     */
    public trace_tools() {
        initComponents();
    }

    public trace_tools(TraceView tv) {
        //super(parent, modal);
        this.Tv = tv;
        initComponents();
        Tv.is_white = Tv.obj.is_white;
        if (Tv.is_white) {
            //  jButton8.setText("Sfondo nero");
        } else {
            //  jButton8.setText("Sfondo bianco");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200, 32767));
        setMinimumSize(new java.awt.Dimension(160, 363));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/lock26.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jToggleButton1, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jToggleButton1.text")); // NOI18N
        jToggleButton1.setMaximumSize(new java.awt.Dimension(65, 65));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(65, 65));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(65, 65));
        jToggleButton1.setRolloverEnabled(false);
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/unlock5.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/WhiteBlack_36.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton8, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton8.text")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/zoomI_out_36.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton7.text")); // NOI18N
        jButton7.setToolTipText(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton7.toolTipText")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/sovra_dromocrone.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton10, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton10.text")); // NOI18N
        jButton10.setToolTipText(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton10.toolTipText")); // NOI18N
        jButton10.setMaximumSize(new java.awt.Dimension(65, 45));
        jButton10.setMinimumSize(new java.awt.Dimension(65, 45));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/undo_3635.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton5.text")); // NOI18N
        jButton5.setToolTipText(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton5.toolTipText")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/zoomI_in_36.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton6.text")); // NOI18N
        jButton6.setToolTipText(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton6.toolTipText")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/zoomT_in_36.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton2.text")); // NOI18N
        jButton2.setToolTipText(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton2.toolTipText")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/AutoPick_36.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/myeditor/zoomT_out_36.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton3.text")); // NOI18N
        jButton3.setToolTipText(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jButton3.toolTipText")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/select.png"))); // NOI18N
        jToggleButton2.setActionCommand(org.openide.util.NbBundle.getMessage(trace_tools.class, "trace_tools.jToggleButton2.actionCommand")); // NOI18N
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setMaximumSize(new java.awt.Dimension(65, 65));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(65, 65));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(65, 65));
        jToggleButton2.setRolloverEnabled(false);
        jToggleButton2.setHorizontalAlignment (SwingConstants.CENTER);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/delete-symbol-option.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(65, 65));
        jButton1.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton1.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        Tv.setLock(this.jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Tv.is_white = !Tv.is_white;
        Tv.obj.is_white = !Tv.obj.is_white;
        if (Tv.is_white) {
            Tv.setBackground(Color.WHITE);
            // jButton8.setText("Sfondo nero");
        } else {
            Tv.setBackground(Color.BLACK);
            // jButton8.setText("Sfondo bianco");
        }

        TopComponent tc ;//= WindowManager.getDefault().findTopComponent("MyViewerTopComponent");
       // Lookup tcLookup = tc.getLookup();
/*        ((MyViewerTopComponent) tc).gmview.is_white = Tv.is_white;
        ((MyViewerTopComponent) tc).gmview.invalidate();
        ((MyViewerTopComponent) tc).gmview.repaint();*/

        // this.setVisible(false);
        Tv.undo();
        Tv.repaint();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (Tv.getSelectionMode()) {
            FirstBrakeList fb_element = Tv.obj.TraceGroup.get(Tv.obj.trace_index);
            for (ZoomTraceUtil zu : fb_element.zoomTr) {
                if (zu.is_selected) {
                    zu.zoom_factor = zu.zoom_factor / 1.2;
                }

            }

        } else {

            Tv.scaleX = 1;
            Tv.resized(Tv.getWidth(), Tv.getHeight());

            Tv.avgMAX = false;
//        this.setVisible(false);
            Tv.undo();
            
        }
        Tv.repaint();
        Tv.invalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Tv.drawDromo = !Tv.drawDromo;
        Tv.repaint();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Tv.undo();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        if (Tv.getSelectionMode()) {
            FirstBrakeList fb_element = Tv.obj.TraceGroup.get(Tv.obj.trace_index);
            for (ZoomTraceUtil zu : fb_element.zoomTr) {
                if (zu.is_selected) {
                    zu.zoom_factor = zu.zoom_factor * 1.2;
                }

            }

        } else {
            if (Tv.avgMAX == false && Tv.scaleX == 1) {
                Tv.avgMAX = true;
            } else {

                Tv.avgMAX = false;
                Tv.scaleX = Tv.scaleX * 1.2;
            }
        }
        //this.setVisible(false);
        Tv.resized(Tv.getWidth(), Tv.getHeight());

        // Tv.undo();
        Tv.repaint();
        Tv.invalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tv.scaleY = (Tv.scaleY * 2);
        Tv.resized(Tv.getWidth(), Tv.getHeight());
        //this.setVisible(false);
        Tv.undo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        welcomeTopComponent welcomeTC = (welcomeTopComponent) WindowManager.getDefault()
                .findTopComponent("welcomeTopComponent");
        if (welcomeTC != null) 
            Tv.autoPick_2(welcomeTC.ltasta_par.lra, welcomeTC.ltasta_par.sra, welcomeTC.ltasta_par.thrs);
            
        
        //this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Tv.scaleY = (1);
        Tv.resized(Tv.getWidth(), Tv.getHeight());
        //this.setVisible(false);
        Tv.undo();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void setTraceView(TraceView m_tv) {
        Tv = m_tv;
    }

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        Tv.setSelectionMode(jToggleButton2.isSelected());
        Tv.repaint();
        Tv.invalidate();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Tv.getSelectionMode()) {
            FirstBrakeList fb_element = Tv.obj.TraceGroup.get(Tv.obj.trace_index);
            int i = 0;
            for (ZoomTraceUtil zu : fb_element.zoomTr) {
                if (zu.is_selected) {
                    fb_element.fb[i].enabled=!fb_element.fb[i].enabled;
                }
                i++;
            }

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private TraceView Tv;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    public TraceView getTraceView() {
        return Tv;

    }

    public void setSelectButtonStatus(boolean isselected) {
        jToggleButton2.setSelected(isselected);
    }
}
