/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.sidebar;

import it.vs30.smartRefract.drawing.DrawDromocrone;
import it.vs30.smartRefract.utils.dromoSelection;
import it.vs30.smartUI.JTX_view;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.myorg.myapi.APIObject;

/**
 *
 * @author PC
 */
public class tx_tool extends javax.swing.JPanel {

    private APIObject obj;
    private JTX_view mTX_view;

    /**
     * Creates new form tx_tool
     */
    public tx_tool() {
        initComponents();
        ImageIcon image_One = new ImageIcon(this.getClass().getResource("/it/vs30/sidebar/one67.png"));
        jToggleButton4.setIcon(image_One);
        ImageIcon image_Two = new ImageIcon(this.getClass().getResource("/it/vs30/sidebar/two8.png"));
        jToggleButton2.setIcon(image_Two);
        ImageIcon image_Three = new ImageIcon(this.getClass().getResource("/it/vs30/sidebar/three1.png"));
        jToggleButton3.setIcon(image_Three);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton8 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();

        setMinimumSize(new java.awt.Dimension(180, 200));

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setLabel(org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton3.label")); // NOI18N
        jToggleButton3.setMinimumSize(new java.awt.Dimension(76, 76));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(76, 76));
        jToggleButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton3StateChanged(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setLabel(org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton4.label")); // NOI18N
        jToggleButton4.setMinimumSize(new java.awt.Dimension(76, 76));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(76, 76));
        jToggleButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton4StateChanged(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setLabel(org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton5.label")); // NOI18N
        jToggleButton5.setMinimumSize(new java.awt.Dimension(76, 76));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(76, 76));
        jToggleButton5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jToggleButton5PropertyChange(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton2.setLabel(org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton2.label")); // NOI18N
        jToggleButton2.setMinimumSize(new java.awt.Dimension(76, 76));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(76, 76));
        jToggleButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton2StateChanged(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/photo134.png"))); // NOI18N
        jButton8.setMaximumSize(new java.awt.Dimension(65, 65));
        jButton8.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton8.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/right-arrow(2).png"))); // NOI18N
        jToggleButton1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jToggleButton1, org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton1.text")); // NOI18N
        jToggleButton1.setToolTipText(org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton1.toolTipText")); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/right-arrow(1).png"))); // NOI18N
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/left-arrow(2).png"))); // NOI18N
        jToggleButton6.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jToggleButton6, org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton6.text")); // NOI18N
        jToggleButton6.setToolTipText(org.openide.util.NbBundle.getMessage(tx_tool.class, "tx_tool.jToggleButton6.toolTipText")); // NOI18N
        jToggleButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/it/vs30/sidebar/left-arrow(1).png"))); // NOI18N
        jToggleButton6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton6StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton2StateChanged
        // TODO add your handling code here:
        //jToggleButton4.setSelected(!jToggleButton2.isSelected());
        //jToggleButton3.setSelected(!jToggleButton2.isSelected());
        if (jToggleButton2.isSelected()) {
            txV.selected = 2;
        }

    }//GEN-LAST:event_jToggleButton2StateChanged

    private void jToggleButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton4StateChanged
        // TODO add your handling code here:
        //jToggleButton2.setSelected(!jToggleButton4.isSelected());
        //jToggleButton3.setSelected(!jToggleButton4.isSelected());

        if (jToggleButton4.isSelected()) {
            txV.selected = 1;
        }

    }//GEN-LAST:event_jToggleButton4StateChanged

    private void jToggleButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton3StateChanged
        // TODO add your handling code here
        //jToggleButton2.setSelected(!jToggleButton3.isSelected());
        //jToggleButton4.setSelected(!jToggleButton3.isSelected());

        if (jToggleButton3.isSelected()) {
            txV.selected = 3;
        }

    }//GEN-LAST:event_jToggleButton3StateChanged

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        // jToggleButton2.setSelected(!jToggleButton2.isSelected());
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jToggleButton5PropertyChange
        // TODO add your handling code here:
        if (jToggleButton3.isSelected()) {
            txV.selected = 0;
        } else {
            // txV.selected=0;
        }

    }//GEN-LAST:event_jToggleButton5PropertyChange

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        /*MyEditor editor = new MyEditor();
         editor.open();
         editor.requestActive();*/
        fc.setFileFilter(new PNGFileFilter());
        fc.setMultiSelectionEnabled(true);


        //      proj.checkLic();
        if (/*proj.licenza*/true) {
            int returnVal = fc.showSaveDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                BufferedImage im_s = new BufferedImage(1400, 1000, BufferedImage.TYPE_INT_RGB);   //    (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

                Graphics offg = im_s.getGraphics();
                Graphics2D g2 = (Graphics2D) offg.create();

                g2.setBackground(Color.white);
                g2.clearRect(0, 0, 1400, 1000);

                DrawDromocrone dd = new DrawDromocrone((obj.proj), obj);

                dd.drawDr(offg, 1400, 1000, true);
                //dv.drawSezione(offg, 2000, 1450);

                try {
                    // retrieve image

                    File outputfile = fc.getSelectedFile();

                    if (!outputfile.getPath().toLowerCase().endsWith(".png")) {
                        outputfile = new File(outputfile.getPath() + ".png");
                    }
                    ImageIO.write(im_s, "png", outputfile);
                } catch (IOException e) {
                }
            }

        }

        // sV.repaint();
    }

    void setAPIObject(APIObject active) {
        this.obj = active;
    }

    public void setTTview(JTX_view txV) {
        mTX_view=txV;
            
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    class PNGFileFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File f) {
            return f.isDirectory() || f.getName().toLowerCase().endsWith(".png");
        }

        @Override
        public String getDescription() {
            return "PNG image file";
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        // TODO add your handling code here:
        System.out.println("Forward visibile: "+txV.forward+"");
        txV.forward=jToggleButton1.isSelected();
        mTX_view.andata=txV.forward;
        mTX_view.invalidate();
        mTX_view.repaint();
        
    }//GEN-LAST:event_jToggleButton1StateChanged

    private void jToggleButton6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton6StateChanged
        // TODO add your handling code here:
         System.out.println("Reverse visibile: "+txV.reverse+"");
        txV.reverse=jToggleButton6.isSelected();
        mTX_view.ritorno = txV.reverse;
        mTX_view.invalidate();
        mTX_view.repaint();
        
        
    }//GEN-LAST:event_jToggleButton6StateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables

    private dromoSelection txV = null;

    public void setTXView(dromoSelection m_txV) {
        this.txV = m_txV;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
