/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package it.vs30.myeditor;

import it.vs30.smartRefract.utils.Bool;
import java.awt.Color;
import org.myorg.myapi.Indagine;

/**
 *
 * @author pitta1981
 */
public class adjust_rec_tTimes extends javax.swing.JDialog {
    private
        Indagine proj;
    private JPhantoming_view phant_view;
    private Bool[] man_phnt_visible;
    private Bool[] is_visible;
    
    /** Creates new form adjust_rec_tTimes */
    public adjust_rec_tTimes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        phant_view = new JPhantoming_view();
        jPanel1.add(phant_view);
    }
    
    public adjust_rec_tTimes(java.awt.Frame parent, boolean modal, Indagine prj) {
        super(parent, modal);
        initComponents();
        proj = prj;
        Color[] color = new Color[255];
        for (int i = 0; i < 255; i++) {
            color[i] = new Color((int) (155 * Math.random()), (int) (185 * Math.random()), (int) (200 * Math.random()));
        }
        color[1] = new Color(50, 175, 165);
        color[2] = new Color(220, 40, 40);
        proj.buildShots();

      //  Bool[] phnt_visible = new Bool[3];
        man_phnt_visible = new Bool[3];
        is_visible = new Bool[3];
        for (int i = 0; i < 3; i++) {
            man_phnt_visible[i] = new Bool();
 //           phnt_visible[i] = new Bool();
            is_visible[i] = new Bool();       
        }
//        phnt_visible[1].setValue( true );
        is_visible[1].setValue( true );
   //     proj.useManPhant
        
        phant_view = new JPhantoming_view(proj, color, is_visible, man_phnt_visible);
        System.out.println(proj.VfB_A[1].tAB);
        System.out.println(proj.VfB_R[1].tAB);
        
        jPanel1.add(phant_view);
        phant_view.invalidate();
        phant_view.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(240, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 394));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));
        jSpinner1.setMinimumSize(new java.awt.Dimension(128, 32));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner1PropertyChange
        // TODO add your handling code here:
     //   System.out.print(jSpinner1.getValue());
        
    }//GEN-LAST:event_jSpinner1PropertyChange

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

}
