/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.myeditor;

import it.vs30.smartRefract.refraction.GRM;
import it.vs30.smartUI.JCustom_layer_chooser;
import it.vs30.smartRefract.utils.Bool;
import it.vs30.smartRefract.utils.FB_set;
import it.vs30.smartRefract.utils.JShot;
import it.vs30.smartUI.JShiftFB;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.ArrayList;

import org.myorg.myapi.FirstBrake;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;
import org.openide.util.Exceptions;

/**
 *
 * @author PC
 */
public class FineTuning extends javax.swing.JDialog {

    private JPhantoming_view phant_view = null;
    public Bool[] layer_edit = new Bool[3];
    public int[] base_shot = null;
    public boolean edit = false;
    private int edit_index = 0;
    private Bool[] man_phnt_visible = new Bool[3];
    private Bool[] is_visible = new Bool[3];
    protected JtV_draw tv_Draw = null;
    private Jsezdlg parentDlg;
    protected JtV_draw tg_Draw = null;
    private JSezioneView sV;

    /**
     * Creates new form FineTuning
     */
    public FineTuning() {
        initComponents();
        phant_view = new JPhantoming_view();
        jPanel5.add(phant_view);
        tv_Draw = new JtV_draw();
        jPanel10.add(tv_Draw);
    }

    public FineTuning(Indagine proj) {
        initComponents();

        tv_Draw = new JtV_draw();
        tg_Draw = new JtV_draw();
        jPanel10.add(tv_Draw);
        jPanel13.add(tg_Draw);
        tv_Draw.sel1 = (int) (proj.xy / proj.stesa.get(0).spaz);
        tv_Draw.sel2 = (int) (proj.xy2 / proj.stesa.get(0).spaz);

        Color[] color = new Color[255];
        for (int i = 0; i < 255; i++) {
            color[i] = new Color((int) (155 * Math.random()), (int) (185 * Math.random()), (int) (200 * Math.random()));
        }
        color[1] = new Color(50, 175, 165);
        color[2] = new Color(220, 40, 40);
        proj.buildShots();

        Bool[] phnt_visible = new Bool[3];
        man_phnt_visible = new Bool[3];
        for (int i = 0; i < 3; i++) {
            man_phnt_visible[i] = new Bool();
            phnt_visible[i] = new Bool();
            is_visible[i] = new Bool();
            layer_edit[i] = new Bool();
            layer_edit[i].setValue(false);
        }

        JCustom_layer_chooser[] clc = new JCustom_layer_chooser[2];
        clc[0] = new JCustom_layer_chooser("Layer1", clc, 0, phnt_visible[1]);


        clc[1] = new JCustom_layer_chooser("Layer2", clc, 1, phnt_visible[2]);
        clc[0].jRadioButton1.setEnabled(false);
        clc[1].jRadioButton1.setEnabled(false);
        jPanel6.add(clc[0]);
        jPanel6.add(clc[1]);
        JCustom_layer_chooser[] man_phant_chooser = new JCustom_layer_chooser[2];
        man_phant_chooser[0] = new JCustom_layer_chooser("Layer1", man_phant_chooser, 0, man_phnt_visible[1]);
        man_phant_chooser[1] = new JCustom_layer_chooser("Layer2", man_phant_chooser, 1, man_phnt_visible[2]);
        jPanel8.add(man_phant_chooser[0]);
        jPanel8.add(man_phant_chooser[1]);
        jCustom_Base_Shot1.jLabel1.setText("Forward baseshot");
        jCustom_Base_Shot1.isForward = true;
        jCustom_Base_Shot2.jLabel1.setText("Reverse baseshot");
        jCustom_Base_Shot2.isForward = false;
        //jPanel6.remove(clc[0]);
        base_shot = find_baseShot(proj);

        phant_view = new JPhantoming_view(proj, color, is_visible, man_phnt_visible, base_shot);

        jCustom_Base_Shot1.setPhntViewer(phant_view);
        jCustom_Base_Shot2.setPhntViewer(phant_view);
        clc[0].setPhntViewer(phant_view);
        clc[1].setPhntViewer(phant_view);
        clc[0].setFineTuning(this);
        clc[1].setFineTuning(this);
        man_phant_chooser[0].setPhntViewer(phant_view);
        man_phant_chooser[1].setPhntViewer(phant_view);
        man_phant_chooser[0].setFineTuning(this);
        man_phant_chooser[1].setFineTuning(this);
        this.setProj(proj);
        init_status();

        jPanel5.add(phant_view);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        auto_phantom_layer1 = new javax.swing.JRadioButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        man_phantom_layer1 = new javax.swing.JRadioButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jCustom_Base_Shot1 = new it.vs30.smartUI.JCustom_Base_Shot();
        jCustom_Base_Shot2 = new it.vs30.smartUI.JCustom_Base_Shot();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        button_saveTx = new javax.swing.JButton();
        reset_Tx = new javax.swing.JButton();
        auto_fix_tx = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        button_apply = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(847, 600));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jSplitPane1.setDividerLocation(350);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jPanel5);

        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 480));

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 430));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 500));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel6.border.title"))); // NOI18N
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setName("Automatic phantoming"); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(240, 69));

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jCheckBox1.text")); // NOI18N
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(auto_phantom_layer1);
        auto_phantom_layer1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(auto_phantom_layer1, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.auto_phantom_layer1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox2, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jCheckBox2.text")); // NOI18N
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        buttonGroup4.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton6, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(auto_phantom_layer1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auto_phantom_layer1)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jRadioButton6)
                    .addComponent(jLabel3))
                .addContainerGap(3, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel8.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox3, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jCheckBox3.text")); // NOI18N
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        buttonGroup3.add(man_phantom_layer1);
        org.openide.awt.Mnemonics.setLocalizedText(man_phantom_layer1, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.man_phantom_layer1.text")); // NOI18N
        man_phantom_layer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_phantom_layer1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox4, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jCheckBox4.text")); // NOI18N
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });

        buttonGroup4.add(jRadioButton8);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton8, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jLabel5.text")); // NOI18N

        buttonGroup5.add(jRadioButton9);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton9, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton9.text")); // NOI18N
        jRadioButton9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton9ItemStateChanged(evt);
            }
        });

        buttonGroup5.add(jRadioButton10);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton10, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton10.text")); // NOI18N
        jRadioButton10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton10ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(man_phantom_layer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton9))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(man_phantom_layer1)
                    .addComponent(jRadioButton9)
                    .addComponent(jCheckBox3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton10)
                    .addComponent(jLabel5)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        jPanel1.setMinimumSize(new java.awt.Dimension(219, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCustom_Base_Shot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCustom_Base_Shot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCustom_Base_Shot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jCustom_Base_Shot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(240, 200));

        jPanel7.setMaximumSize(new java.awt.Dimension(240, 32767));
        jPanel7.setMinimumSize(new java.awt.Dimension(10, 400));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 800));
        jScrollPane2.setViewportView(jPanel7);

        org.openide.awt.Mnemonics.setLocalizedText(button_saveTx, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.button_saveTx.text")); // NOI18N
        button_saveTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveTxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(reset_Tx, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.reset_Tx.text")); // NOI18N
        reset_Tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_TxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(auto_fix_tx, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.auto_fix_tx.text")); // NOI18N
        auto_fix_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auto_fix_txActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(reset_Tx, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_saveTx)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(auto_fix_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_saveTx)
                    .addComponent(reset_Tx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(auto_fix_tx)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jSplitPane1.TabConstraints.tabTitle"), jSplitPane1); // NOI18N

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jSplitPane2.setRightComponent(jPanel10);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(200, 100));

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 348));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel12.border.title"))); // NOI18N
        jPanel12.setMaximumSize(new java.awt.Dimension(200, 46));
        jPanel12.setMinimumSize(new java.awt.Dimension(200, 46));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(jRadioButton1);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton1.text")); // NOI18N
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton2, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton2.text")); // NOI18N
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jRadioButton2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel4.border.title"))); // NOI18N
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup2.add(jRadioButton3);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton3, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton3.text")); // NOI18N
        jRadioButton3.setEnabled(false);
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });
        jPanel4.add(jRadioButton3);

        buttonGroup2.add(jRadioButton4);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton4, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton4.text")); // NOI18N
        jRadioButton4.setEnabled(false);
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton4);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel11.border.title"))); // NOI18N
        jPanel11.setMinimumSize(new java.awt.Dimension(0, 120));
        jPanel11.setPreferredSize(new java.awt.Dimension(222, 200));

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jLabel2.text")); // NOI18N

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jSpinner1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel9);

        jSplitPane2.setLeftComponent(jScrollPane3);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jSplitPane2.TabConstraints.tabTitle"), jSplitPane2); // NOI18N

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());
        jSplitPane3.setRightComponent(jPanel13);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 100));

        jPanel14.setPreferredSize(new java.awt.Dimension(300, 348));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel15.border.title"))); // NOI18N
        jPanel15.setMaximumSize(new java.awt.Dimension(200, 46));
        jPanel15.setMinimumSize(new java.awt.Dimension(200, 46));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(jRadioButton11);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton11, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton11.text")); // NOI18N
        jRadioButton11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton11ItemStateChanged(evt);
            }
        });
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel15.add(jRadioButton11);

        buttonGroup1.add(jRadioButton12);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton12, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton12.text")); // NOI18N
        jRadioButton12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton12StateChanged(evt);
            }
        });
        jRadioButton12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton12ItemStateChanged(evt);
            }
        });
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel15.add(jRadioButton12);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel16.border.title"))); // NOI18N
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup2.add(jRadioButton13);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton13, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton13.text")); // NOI18N
        jRadioButton13.setEnabled(false);
        jRadioButton13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton13ItemStateChanged(evt);
            }
        });
        jPanel16.add(jRadioButton13);

        buttonGroup2.add(jRadioButton14);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton14, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jRadioButton14.text")); // NOI18N
        jRadioButton14.setEnabled(false);
        jRadioButton14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton14ItemStateChanged(evt);
            }
        });
        jPanel16.add(jRadioButton14);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel17.border.title"))); // NOI18N
        jPanel17.setMinimumSize(new java.awt.Dimension(0, 120));
        jPanel17.setPreferredSize(new java.awt.Dimension(222, 200));

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jLabel6.text")); // NOI18N

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jSpinner2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane4.setViewportView(jPanel14);

        jSplitPane3.setLeftComponent(jScrollPane4);

        jPanel3.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(button_apply, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.button_apply.text")); // NOI18N
        button_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_applyActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(FineTuning.class, "FineTuning.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_apply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_apply)
                    .addComponent(jButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 0) {
            try {
                init_status();
            } catch (Exception ex) {
                System.out.println("Exception " + ex.getMessage() + "\ninit_status");
            }
        }
        if (jTabbedPane1.getSelectedIndex() == 1) {
            if (dati_sismici.man_Phant_and[0].fb.length == 0) {
                jRadioButton2.setEnabled(false);
            } else {
                jRadioButton2.setEnabled(true);
            }
        }
        if (jTabbedPane1.getSelectedIndex() == 2) {
            if (dati_sismici.man_Phant_and[0].fb.length == 0) {
                jRadioButton12.setEnabled(false);
            } else {
                jRadioButton12.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        System.out.println("Spinner xy: " + jSpinner1.getValue());
        if (jRadioButton3.isSelected()) {
            tv_Draw.sel1 = (Integer) jSpinner1.getValue();
        } else if (jRadioButton4.isSelected()) {
            tv_Draw.sel2 = (Integer) jSpinner1.getValue();

        }

        //   proj.xy2 = (Double) jSpinner1.getValue();
        //   proj.Tv2 = proj.DTTv(2, proj.xy2);
        //   this.tvdraw.tV2 = proj.Tv2;
        this.tv_Draw.invalidate();
        this.tv_Draw.repaint();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()) {
            GRM grm = new GRM();
            jSpinner1.setValue(grm.getBestXYTv(tv_Draw.tV1A, dati_sismici.stesa.get(0).spaz));
        }
        if (jRadioButton4.isSelected()) {
            GRM grm = new GRM();
            jSpinner1.setValue(grm.getBestXYTv(tv_Draw.tV2A, dati_sismici.stesa.get(0).spaz));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        int maxXY = dati_sismici.stesa.get(0).ch / 4;
        tv_Draw.tV2A = new double[maxXY][];
        jSpinner1.setValue(tv_Draw.sel2);
        if (jRadioButton2.isSelected()) {
            GRM grm = new GRM();
            double tAB = Math.max(dati_sismici.man_Phant_and[1].tAB, dati_sismici.man_Phant_rit[1].tAB);
            for (int i = 0; i < maxXY; i++) {

                tv_Draw.tV2A[i] = grm.compute_tV(dati_sismici.man_Phant_and[1], dati_sismici.man_Phant_rit[1], tAB, dati_sismici.stesa.get(0).spaz * i);
                //dati_sismici.DTTv(1, ((FirstBrakeList) dati_sismici.stesa.get(0)).spaz * i);
                for (int j = 0; j < tv_Draw.tV2A[i].length; j++) {
                    tv_Draw.tV2A[i][j] = tv_Draw.tV2A[i][j];// + (i * 15);

                }
            }

        } else {
            for (int i = 0; i < tv_Draw.tV2A.length; i++) {

                tv_Draw.tV2A[i] = dati_sismici.DTTv(2, ( dati_sismici.stesa.get(0)).spaz * i);
                for (int j = 0; j < tv_Draw.tV2A[i].length; j++) {
                    tv_Draw.tV2A[i][j] = tv_Draw.tV2A[i][j]; //+ (i * 15);

                }
            }
        }
        tv_Draw.tV1 = null;
        tv_Draw.tV2 = dati_sismici.Tv2;
        tv_Draw.spaz = dati_sismici.stesa.get(0).spaz;
        tv_Draw.invalidate();
        tv_Draw.repaint();
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
        // TODO add your handling code here:
        int maxXY = dati_sismici.stesa.get(0).ch / 4;
        jSpinner1.setValue(tv_Draw.sel1);
        tv_Draw.tV1A = new double[maxXY][];
        if (jRadioButton2.isSelected()) {
            GRM grm = new GRM();
            double tAB = Math.max(dati_sismici.man_Phant_and[0].tAB, dati_sismici.man_Phant_rit[0].tAB);
            for (int i = 0; i < maxXY; i++) {

                tv_Draw.tV1A[i] = grm.compute_tV(dati_sismici.man_Phant_and[0], dati_sismici.man_Phant_rit[0], tAB, dati_sismici.stesa.get(0).spaz * i);
                //dati_sismici.DTTv(1, ((FirstBrakeList) dati_sismici.stesa.get(0)).spaz * i);
                for (int j = 0; j < tv_Draw.tV1A[i].length; j++) {
                    tv_Draw.tV1A[i][j] = tv_Draw.tV1A[i][j];// + (i * 15);

                }
            }

        } else {
            for (int i = 0; i < tv_Draw.tV1A.length; i++) {

                tv_Draw.tV1A[i] = dati_sismici.DTTv(1, ( dati_sismici.stesa.get(0)).spaz * i);
 /*               for (int j = 0; j < tv_Draw.tV1A[i].length; j++) {
                    tv_Draw.tV1A[i][j] = tv_Draw.tV1A[i][j];// + (i * 15);

                }*/
            }
        }
        tv_Draw.tV1 = dati_sismici.Tv1;
        tv_Draw.tV2 = null;
        tv_Draw.spaz = dati_sismici.stesa.get(0).spaz;

        tv_Draw.invalidate();
        tv_Draw.repaint();
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        if (jRadioButton2.isSelected()) {
            if (dati_sismici.man_Phant_and[0].fb.length == dati_sismici.stesa.get(0).ch
                    && dati_sismici.man_Phant_and[0].fb[0].time >= 0) {
                jRadioButton3.setEnabled(true);
            } else {
                jRadioButton3.setEnabled(false);
            }
            if (dati_sismici.man_Phant_and[1].fb.length == dati_sismici.stesa.get(0).ch
                    && dati_sismici.man_Phant_and[1].fb[0].time >= 0) {
                jRadioButton4.setEnabled(true);
            } else {
                jRadioButton4.setEnabled(false);
            }

        }
        tv_Draw.invalidate();
        tv_Draw.repaint();
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            if (dati_sismici.VfB_A[1].fb.length == dati_sismici.stesa.get(0).ch) {
                jRadioButton3.setEnabled(true);
            } else {
                jRadioButton3.setEnabled(false);
            }
            if (dati_sismici.VfB_A[2].fb.length == dati_sismici.stesa.get(0).ch) {
                jRadioButton4.setEnabled(true);
            } else {
                jRadioButton4.setEnabled(false);
            }

        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void button_saveTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveTxActionPerformed
        // TODO add your handling code here:
        int i = 0;
        int chanel = dati_sismici.stesa.get(0).ch;
        dati_sismici.init_man_phantoming(chanel, dati_sismici.stesa,false);

        i = 0;
        for (JShot shot : dati_sismici.shots) {
            i++;

            for (FB_set fbs : shot.FB_sets) {
                if (fbs.layer == (edit_index + 2) && fbs.used) {
                    for (FirstBrake fb : fbs.fb) {
                        if (fbs.dir > 0) {
                            FirstBrakeList fbl = dati_sismici.man_Phant_and[fbs.layer - 2];
                            if (fbl.fb[fb.chan].offset >= Math.abs(fb.posx - fbs.xshot)) {
                                //man_Phant_and.fb[fb.chan] = fb;
                                fbl.fb[fb.chan].time = fb.time + fbs.shift;
                                fbl.fb[fb.chan].offset = Math.abs(fb.posx - fbs.xshot);
                            }
                        } else {
                            FirstBrakeList fbl = dati_sismici.man_Phant_rit[fbs.layer - 2];
                            if (fbl.fb[fb.chan].offset >= Math.abs(fb.posx - fbs.xshot)) {
                                //man_Phant_and.fb[fb.chan] = fb;
                                fbl.fb[fb.chan].time = fb.time + fbs.shift;
                                fbl.fb[fb.chan].offset = Math.abs(fb.posx - fbs.xshot);
                            }
                        }
                    }

                    //break;
                }
            }
        }
        fillTT(dati_sismici.man_Phant_and[edit_index].fb);
        fillTT(dati_sismici.man_Phant_rit[edit_index].fb);
        dati_sismici.man_Phant_and[edit_index].scoppio = dati_sismici.stesa.get(base_shot[0]).scoppio;
        dati_sismici.man_Phant_rit[edit_index].scoppio = dati_sismici.stesa.get(base_shot[1]).scoppio;
        dati_sismici.man_Phant_and[edit_index].tAB = dati_sismici.man_Phant_and[edit_index].getT(dati_sismici.stesa.get(base_shot[1]).scoppio);
        dati_sismici.man_Phant_rit[edit_index].tAB = dati_sismici.man_Phant_rit[edit_index].getT(dati_sismici.stesa.get(base_shot[0]).scoppio);
        init_status();
//        return;
    }//GEN-LAST:event_button_saveTxActionPerformed

    private void button_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_applyActionPerformed
        // TODO add your handling code here:
        dati_sismici.xy = this.tv_Draw.sel1 * dati_sismici.stesa.get(0).spaz;
        dati_sismici.xy2 = this.tv_Draw.sel2 * dati_sismici.stesa.get(0).spaz;

        if (auto_phantom_layer1.isSelected()) {
            try {
                dati_sismici.phantom(1);
                dati_sismici.useManPhant[0].setValue(false);
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
        } else {
            dati_sismici.VfB_A[1] = dati_sismici.man_Phant_and[0];
            dati_sismici.VfB_R[1] = dati_sismici.man_Phant_rit[0];

            dati_sismici.VfB_R[1].tAB = dati_sismici.VfB_A[1].getT(dati_sismici.VfB_R[1].scoppio);
            dati_sismici.VfB_A[1].tAB = dati_sismici.VfB_R[1].getT(dati_sismici.VfB_A[1].scoppio);


            dati_sismici.useManPhant[0].setValue(true);
        }
        if (jRadioButton6.isSelected()) {
            try {
                dati_sismici.phantom(2);
                dati_sismici.useManPhant[1].setValue(false);
            } catch (Exception ex) {
            }

        } else {
            dati_sismici.VfB_A[2] = dati_sismici.man_Phant_and[1];
            dati_sismici.VfB_R[2] = dati_sismici.man_Phant_rit[1];
            dati_sismici.VfB_R[2].tAB = dati_sismici.VfB_A[2].getT(dati_sismici.VfB_R[1].scoppio);
            dati_sismici.VfB_A[2].tAB = dati_sismici.VfB_R[2].getT(dati_sismici.VfB_A[1].scoppio);


            dati_sismici.useManPhant[1].setValue(true);
        }
        GRM grm = new GRM();
        double[] TxAB = grm.FirstBrakeToDouble(dati_sismici.VfB_A[1].fb);
        double[] TxBA = grm.FirstBrakeToDouble(dati_sismici.VfB_R[1].fb);
        double[] tV = grm.compute_tV(dati_sismici.VfB_A[1], dati_sismici.VfB_R[1], Math.max(dati_sismici.VfB_A[1].tAB, dati_sismici.VfB_R[1].tAB), dati_sismici.xy);

        double v1 = grm.compute_v1(tV, dati_sismici.VfB_A[1].spaz);
        double[] tG = grm.compute_tG(dati_sismici.VfB_A[1], dati_sismici.VfB_R[1], Math.max(dati_sismici.VfB_A[1].tAB, dati_sismici.VfB_R[1].tAB), dati_sismici.xy, v1);
        double v0 = grm.compute_V0(dati_sismici.stesa);
        double[] zz = grm.compute_zz(tG, v1, v0);
        double[] tG2;
        
        if (dati_sismici.VfB_A[2].fb.length == dati_sismici.stesa.get(0).ch) {
            tV = grm.compute_tV(dati_sismici.VfB_A[2], dati_sismici.VfB_R[2], Math.max(dati_sismici.VfB_A[2].tAB, dati_sismici.VfB_R[2].tAB), dati_sismici.xy2);
            double v2 = grm.compute_v1(tV, dati_sismici.VfB_A[1].spaz);
            tG2 = grm.compute_tG(tG, dati_sismici.VfB_A[2], dati_sismici.VfB_R[2], Math.max(dati_sismici.VfB_A[2].tAB, dati_sismici.VfB_R[2].tAB), dati_sismici.xy, v2);
           // for(int i = 0;i<tG.length; i++){
           //     tG2[i]=tG2[i]-tG[i];
           // }
            
            double[] zz1 = grm.compute_zz(tG2, v2, v1);
            
            
            dati_sismici.Zg2=zz1;
            dati_sismici.V3=v2;
        }

        dati_sismici.Zg1=zz;
        
        
  //      dati_sismici.sezDT(true);
        sV.invalidate();
        sV.repaint();

    }//GEN-LAST:event_button_applyActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        this.is_visible[1].setValue(jCheckBox1.isSelected());


        this.phant_view.invalidate();
        this.phant_view.repaint();
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        this.is_visible[2].setValue(jCheckBox2.isSelected());


        this.phant_view.invalidate();
        this.phant_view.repaint();
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jRadioButton9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton9ItemStateChanged
        // TODO add your handling code here:
        edit = this.jRadioButton9.isSelected();
        setLayer(0, this.jRadioButton9.isSelected());


        if (this.jRadioButton9.isSelected()) {
            addLayerEditable(0);
            this.edit_index = 0;
            // for(int i=0;i<lista.length;i++){
            //     if(i!=self_index){
            //         lista[i].jRadioButton1.setSelected(false);
            //fine.setLayer(self_index,this.jRadioButton1.isSelected());

            //      }
            //  } 
        }


    }//GEN-LAST:event_jRadioButton9ItemStateChanged

    private void jRadioButton10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton10ItemStateChanged
        // TODO add your handling code here:
        edit = this.jRadioButton10.isSelected();
        setLayer(1, this.jRadioButton10.isSelected());


        if (this.jRadioButton10.isSelected()) {
            addLayerEditable(1);
            this.edit_index = 1;
            // for(int i=0;i<lista.length;i++){
            //     if(i!=self_index){
            //         lista[i].jRadioButton1.setSelected(false);
            //fine.setLayer(self_index,this.jRadioButton1.isSelected());

            //      }
            //  } 
        }
    }//GEN-LAST:event_jRadioButton10ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        // TODO add your handling code here:
        man_phnt_visible[1].setValue(jCheckBox3.isSelected());
        phant_view.invalidate();
        phant_view.repaint();


    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        // TODO add your handling code here:
        man_phnt_visible[2].setValue(jCheckBox4.isSelected());
        phant_view.invalidate();
        phant_view.repaint();

    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton11ItemStateChanged
        // TODO add your handling code here:
        if (jRadioButton11.isSelected()) {
            if (dati_sismici.VfB_A[1].fb.length == dati_sismici.stesa.get(0).ch) {
                jRadioButton13.setEnabled(true);
            } else {
                jRadioButton13.setEnabled(false);
            }
            if (dati_sismici.VfB_A[2].fb.length == dati_sismici.stesa.get(0).ch) {
                jRadioButton14.setEnabled(true);
            } else {
                jRadioButton14.setEnabled(false);
            }

        }
    }//GEN-LAST:event_jRadioButton11ItemStateChanged

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton12StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12StateChanged

    private void jRadioButton12ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton12ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ItemStateChanged

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton13ItemStateChanged
        // TODO add your handling code here:
        int maxXY = dati_sismici.stesa.get(0).ch / 4;
        jSpinner2.setValue(tv_Draw.sel1);
        tg_Draw.sel1 = tv_Draw.sel1;
        tg_Draw.tV1A = new double[maxXY][];
        if (jRadioButton12.isSelected()) {
            GRM grm = new GRM();
            double tAB = Math.max(dati_sismici.man_Phant_and[0].tAB, dati_sismici.man_Phant_rit[0].tAB);
            double[] tV = grm.compute_tV(dati_sismici.man_Phant_and[0], dati_sismici.man_Phant_rit[0], tAB, dati_sismici.xy);

            double v1 = grm.compute_v1(tV, dati_sismici.VfB_A[1].spaz);

            for (int i = 0; i < maxXY; i++) {

                tg_Draw.tV1A[i] = grm.compute_tG(dati_sismici.man_Phant_and[0], dati_sismici.man_Phant_rit[0], tAB, dati_sismici.stesa.get(0).spaz * i, v1);
                //dati_sismici.DTTv(1, ((FirstBrakeList) dati_sismici.stesa.get(0)).spaz * i);
                for (int j = 0; j < tg_Draw.tV1A[i].length; j++) {
                    tg_Draw.tV1A[i][j] = tg_Draw.tV1A[i][j];// + (i * 15);

                }
            }

        } else {
            GRM grm = new GRM();

            double[] tV = grm.compute_tV(dati_sismici.VfB_A[1], dati_sismici.VfB_R[1], Math.max(dati_sismici.VfB_A[1].tAB, dati_sismici.VfB_R[1].tAB), dati_sismici.xy);

            double v1 = grm.compute_v1(tV, dati_sismici.VfB_A[1].spaz);

            for (int i = 0; i < maxXY; i++) {
                tg_Draw.tV1A[i] = grm.compute_tG(dati_sismici.VfB_A[1], dati_sismici.VfB_R[1], Math.max(dati_sismici.VfB_A[1].tAB, dati_sismici.VfB_R[1].tAB), dati_sismici.stesa.get(0).spaz * i, v1);


                //tg_Draw.tV1A[i] = dati_sismici.DTTv(1, ((FirstBrakeList) dati_sismici.stesa.get(0)).spaz * i);
                for (int j = 0; j < tg_Draw.tV1A[i].length; j++) {
                    tg_Draw.tV1A[i][j] = tg_Draw.tV1A[i][j];// + (i * 15);

                }
            }
        }
        tg_Draw.tV1 = dati_sismici.Tv1;
        tg_Draw.tV2 = null;
        tg_Draw.spaz = dati_sismici.stesa.get(0).spaz;

        tg_Draw.invalidate();
        tg_Draw.repaint();



    }//GEN-LAST:event_jRadioButton13ItemStateChanged

    private void jRadioButton14ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton14ItemStateChanged
        // TODO add your handling code here:

        int maxXY = dati_sismici.stesa.get(0).ch / 4;
        jSpinner2.setValue(tv_Draw.sel2);
        tg_Draw.sel2 = tv_Draw.sel2;
        tg_Draw.tV1A = new double[maxXY][];
        if (jRadioButton12.isSelected()) {
            GRM grm = new GRM();
            double tAB = Math.max(dati_sismici.man_Phant_and[1].tAB, dati_sismici.man_Phant_rit[1].tAB);
            double[] tV = grm.compute_tV(dati_sismici.man_Phant_and[1], dati_sismici.man_Phant_rit[1], tAB, dati_sismici.xy);

            double v1 = grm.compute_v1(tV, dati_sismici.VfB_A[1].spaz);

            for (int i = 0; i < maxXY; i++) {

                tg_Draw.tV2A[i] = grm.compute_tG(dati_sismici.man_Phant_and[1], dati_sismici.man_Phant_rit[1], tAB, dati_sismici.stesa.get(1).spaz * i, v1);
                //dati_sismici.DTTv(1, ((FirstBrakeList) dati_sismici.stesa.get(0)).spaz * i);
                /*for (int j = 0; j < tg_Draw.tV1A[i].length; j++) {
                 tg_Draw.tV1A[i][j] = tg_Draw.tV1A[i][j];// + (i * 15);

                 }*/
            }

        } else {
            GRM grm = new GRM();

            double[] tV = grm.compute_tV(dati_sismici.VfB_A[2], dati_sismici.VfB_R[2], Math.max(dati_sismici.VfB_A[2].tAB, dati_sismici.VfB_R[2].tAB), dati_sismici.xy);

            double v1 = grm.compute_v1(tV, dati_sismici.VfB_A[2].spaz);

            for (int i = 0; i < maxXY; i++) {
                tg_Draw.tV2A[i] = grm.compute_tG(dati_sismici.VfB_A[2], dati_sismici.VfB_R[2], Math.max(dati_sismici.VfB_A[2].tAB, dati_sismici.VfB_R[2].tAB), dati_sismici.stesa.get(0).spaz * i, v1);


                //tg_Draw.tV1A[i] = dati_sismici.DTTv(1, ((FirstBrakeList) dati_sismici.stesa.get(0)).spaz * i);
            /*    for (int j = 0; j < tg_Draw.tV2A[i].length; j++) {
                 tg_Draw.tV2A[i][j] = tg_Draw.tV2A[i][j];// + (i * 15);

                 }*/
            }
        }
        tg_Draw.tV1 = null;
        tg_Draw.tV2 = dati_sismici.Tv2;
        tg_Draw.spaz = dati_sismici.stesa.get(0).spaz;

        tg_Draw.invalidate();
        tg_Draw.repaint();




    }//GEN-LAST:event_jRadioButton14ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if (jRadioButton13.isSelected()) {
            GRM grm = new GRM();
            jSpinner2.setValue(grm.getBestXYTg(tg_Draw.tV1A, dati_sismici.stesa.get(0).spaz));
        }
        if (jRadioButton14.isSelected()) {
            GRM grm = new GRM();
            jSpinner2.setValue(grm.getBestXYTg(tg_Draw.tV2A, dati_sismici.stesa.get(0).spaz));
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        if (jRadioButton13.isSelected()) {
            tv_Draw.sel1 = (Integer) jSpinner2.getValue();
            tg_Draw.sel1 = tv_Draw.sel1;
        } else if (jRadioButton14.isSelected()) {
            tv_Draw.sel2 = (Integer) jSpinner2.getValue();
            tg_Draw.sel2 = tv_Draw.sel2;
        }
        tg_Draw.invalidate();
        tg_Draw.repaint();

    }//GEN-LAST:event_jSpinner2StateChanged

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void reset_TxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_TxActionPerformed
        // TODO add your handling code here:
        int chanel = dati_sismici.stesa.get(0).ch;
        dati_sismici.init_man_phantoming(chanel, dati_sismici.stesa,true);

        
    }//GEN-LAST:event_reset_TxActionPerformed

    private void auto_fix_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auto_fix_txActionPerformed
        // TODO add your handling code here:
        if (auto_phantom_layer1.isSelected()) {
            try {
                dati_sismici.phantom(1);
                dati_sismici.useManPhant[0].setValue(false);
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
        } else {
            dati_sismici.VfB_A[1] = dati_sismici.man_Phant_and[0];
            dati_sismici.VfB_R[1] = dati_sismici.man_Phant_rit[0];

            dati_sismici.VfB_R[1].tAB = dati_sismici.VfB_A[1].getT(dati_sismici.VfB_R[1].scoppio);
            dati_sismici.VfB_A[1].tAB = dati_sismici.VfB_R[1].getT(dati_sismici.VfB_A[1].scoppio);


            dati_sismici.useManPhant[0].setValue(true);
        }
        double deltaTAB = dati_sismici.VfB_R[1].tAB - dati_sismici.VfB_A[1].tAB;
        
        
        
        
    }//GEN-LAST:event_auto_fix_txActionPerformed

    private void man_phantom_layer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_phantom_layer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_man_phantom_layer1ActionPerformed

    public void setParentDialog(JSezioneView argParent) {
        sV = argParent;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auto_fix_tx;
    private javax.swing.JRadioButton auto_phantom_layer1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton button_apply;
    private javax.swing.JButton button_saveTx;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private it.vs30.smartUI.JCustom_Base_Shot jCustom_Base_Shot1;
    private it.vs30.smartUI.JCustom_Base_Shot jCustom_Base_Shot2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton man_phantom_layer1;
    private javax.swing.JButton reset_Tx;
    // End of variables declaration//GEN-END:variables
    Indagine dati_sismici;

    public void setProj(Indagine proj) {
        dati_sismici = proj;
        dati_sismici.buildShots();
        this.phant_view.setProj(proj);
        System.out.println(proj.VfB_A.length);
    }

    private int[] find_baseShot(Indagine proj) {
        int nshot = proj.stesa.size();
        double distanza_For = 999;
        double distanza_Rev = 999;
        int ind_For = 0;
        int ind_Rev = 0;
        for (int i = 0; i < nshot; i++) {
            FirstBrakeList fbl = proj.stesa.get(i);

            if (fbl.scoppio < fbl.spaz_in) {
                if (Math.abs(fbl.scoppio - fbl.spaz_in) < distanza_For) {
                    distanza_For = Math.abs(fbl.scoppio - fbl.spaz_in);
                    ind_For = i;

                }
            }

            if (fbl.scoppio > fbl.spaz_in + (fbl.spaz * (fbl.ch - 1))) {
                if (Math.abs(fbl.scoppio - fbl.spaz_in) < distanza_Rev) {
                    distanza_Rev = Math.abs(fbl.scoppio - fbl.spaz_in);
                    ind_Rev = i;

                }
            }

        }
        int[] a = {ind_For, ind_Rev};
        //To change body of generated methods, choose Tools | Templates.
        return a;
    }

    public void fillTT(FirstBrake[] mfb) {
        ArrayList<double[]> arData;
        arData = new ArrayList<>();


        int i = 0;
        for (FirstBrake fb : mfb) {
            if (fb.time >= 0) {
                double data[] = new double[2];
                data[0] = fb.posx;
                data[1] = fb.time;
                i++;
                arData.add(data);
            }

        }
        double data[][] = arData.toArray(new double[arData.size()][2]);

        double[] param = FirstBrakeList.getOLSRegression(data);
        i = 0;
        for (FirstBrake fb : mfb) {
            if (fb.time < 0) {
                fb.time = fb.posx * param[1] + param[0];

            }
            i++;
        }

        //FirstBrakeList.getOLSRegression(data1)[1];
    }

    public void setLayer(int self_index) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setLayer(int self_index, boolean selected) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        layer_edit[self_index].setValue(selected);
        this.edit_index = self_index + 2;
        this.edit = selected;
        ArrayList<Integer> shots;
        shots = new ArrayList<>();
        for (int i = 0; i < dati_sismici.stesa.size(); i++) {
            FirstBrakeList fbl =  dati_sismici.stesa.get(i);
            for (int j = 0; j < fbl.fb.length; j++) {
                if (fbl.fb[j].layer == this.edit_index) {
                    shots.add(i);

                    j = fbl.fb.length + 1;
                }
            }
        }

        phant_view.setEditLayer(self_index + 2, this.edit, shots, dati_sismici.shots);
        phant_view.repaint();
    }

    public void addLayerEditable(int self_index) {
        this.jPanel7.removeAll();
        int i=0;
        for (JShot shs : dati_sismici.shots) {
            for (FB_set fbs : shs.FB_sets) {
                if (fbs.layer == (self_index + 2)) {
                    this.jPanel7.add(new JShiftFB(fbs, phant_view));
                    // ,break;
                    i++;
                }
            }
        }
        jPanel7.setPreferredSize(new Dimension(230,i*36));
        jPanel7.updateUI();
    }

    private void init_status() {


        if (dati_sismici.VfB_A[2].fb.length == dati_sismici.stesa.get(0).ch) {
            jRadioButton10.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton8.setEnabled(true);
            
        } else {
            jRadioButton10.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jRadioButton6.setEnabled(false);
            jRadioButton8.setEnabled(false);
            
            
        }




        if (dati_sismici.man_Phant_and[0].fb.length > 0) {
            if (dati_sismici.man_Phant_and[0].fb.length == dati_sismici.stesa.get(0).ch
                    && dati_sismici.man_Phant_and[0].fb[0].time >= 0) {
                jCheckBox3.setEnabled(true);
                //    jRadioButton3.setEnabled(true);
            } else {
                jCheckBox3.setEnabled(false);
                //    jRadioButton3.setEnabled(false);
            }
        } else {
            jCheckBox3.setEnabled(false);
        }
        if (dati_sismici.man_Phant_and[1].fb.length > 0) {
            if (dati_sismici.man_Phant_and[1].fb.length == dati_sismici.stesa.get(0).ch
                    && dati_sismici.man_Phant_and[1].fb[0].time >= 0) {
                jCheckBox4.setEnabled(true);
                //    jRadioButton3.setEnabled(true);
            } else {
                jCheckBox4.setEnabled(false);
                //    jRadioButton3.setEnabled(false);
            }
        } else {
            jCheckBox4.setEnabled(false);
        }

        auto_phantom_layer1.setSelected(!dati_sismici.useManPhant[0].getValue());

    }
}
