/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.myeditor;

import it.vs30.smartRefract.utils.Bool;

/**
 *
 * @author PC
 */
public class JCustom_layer_chooser extends javax.swing.JPanel {
    protected Bool is_visible=null;
    protected JPhantoming_view jPhant_view=null;
    /**
     * Creates new form JCustom_layer_chooser
     */
    
    
    public JCustom_layer_chooser() {
        initComponents();
    }
    
    public JCustom_layer_chooser(String name,JCustom_layer_chooser[] lista,int self_index,Bool is_visible)
    {
        initComponents();
        jLabel1.setText(name);
        this.lista=lista;
        this.self_index=self_index;
        this.is_visible=is_visible;
        this.jCheckBox1.setSelected(is_visible.getValue());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(JCustom_layer_chooser.class, "JCustom_layer_chooser.jCheckBox1.text")); // NOI18N
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(JCustom_layer_chooser.class, "JCustom_layer_chooser.jRadioButton1.text")); // NOI18N
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JCustom_layer_chooser.class, "JCustom_layer_chooser.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        if(this.jRadioButton1.isSelected()){
           for(int i=0;i<lista.length;i++){
               if(i!=self_index){
                   lista[i].jRadioButton1.setSelected(false);
               }
           } 
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        this.is_visible.setValue(jCheckBox1.isSelected());
        this.jPhant_view.invalidate();
        this.jPhant_view.repaint();
        
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
    JCustom_layer_chooser[] lista;
    int self_index;

    void setPhntViewer(JPhantoming_view phant_view) {
        jPhant_view=phant_view; //To change body of generated methods, choose Tools | Templates.
    }
}
