/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Jgeometria_av.java
 *
 * Created on 23-lug-2012, 22.48.36
 */
package it.vs30.myeditor;

import java.awt.Dimension;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;

/**
 *
 * @author user
 */
public class Jgeometria_av extends javax.swing.JDialog {

    /** Creates new form Jgeometria_av */
    public Jgeometria_av(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Jgeometria_av() {
    //    super(parent, modal);
        initComponents();
    }
    
    final MyTableModel tm = new MyTableModel();
    
    
    
    Indagine prj;
    
    
    public void setTable(Indagine proj) {



        String geom = "";

         
        prj=proj;

        for (int i = 0; i < proj.stesa.size(); i++) {
            FirstBrakeList fbl = proj.stesa.get(i);
            //fbl.scoppio=Double.parseDouble(geom[i].replace('m', '\0'));
          //  tm.addData(new Data("" +(new File(fbl.fbp)).getName(), "" + fbl.scoppio));
            tm.spaz = fbl.spaz;
            tm.spaz_in = fbl.spaz_in;
            tm.ch = fbl.ch;
          //  geom = geom + " " + getGeom(fbl.spaz_in, fbl.spaz, fbl.scoppio, fbl.ch);
        }
        Data dt=new Data(tm.ch);
        for (int i = 0; i < proj.stesa.size(); i++) {
            FirstBrakeList fbl = proj.stesa.get(i);
            for(int j=0;j<fbl.fb.length;j++){
                dt.x[j]=fbl.fb[j].posx;
                
            }
        }
        
        tm.addData(dt);
        dt=new Data(tm.ch);
        for (int i = 0; i < proj.stesa.size(); i++) {
            FirstBrakeList fbl = proj.stesa.get(i);
            for(int j=0;j<fbl.fb.length;j++){
                dt.x[j]=fbl.fb[j].z;
                
            }
        }
        
        tm.addData(dt);
        

        //final JTable jTable1 = new JTable(tm);
        jTable1.setModel(tm);
        jTable1.setPreferredScrollableViewportSize(new Dimension(1000, 700));

        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getModel().addTableModelListener(new MyTableModelListener(jTable1));



        //       jTable1.setFillsViewportHeight(true); 
 /*
         * JScrollPane jScrollPane2=new JScrollPane(jTable1);
         * jScrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
         * jPanel2.add(jScrollPane2);
         */
        //jPanel1.add(jTable1);
        // jTable1.setColumnModel(new TableColumnModel());

    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jButton1.setEnabled(false);
        jButton1.setLabel(org.openide.util.NbBundle.getMessage(Jgeometria_av.class, "Jgeometria_av.jButton1.label")); // NOI18N

        jButton2.setText(org.openide.util.NbBundle.getMessage(Jgeometria_av.class, "Jgeometria_av.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(org.openide.util.NbBundle.getMessage(Jgeometria_av.class, "Jgeometria_av.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(623, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < prj.stesa.size(); i++) {
            FirstBrakeList fbl = prj.stesa.get(i);
            for(int j=0;j<fbl.fb.length;j++){
                fbl.fb[j].z=(Double)tm.getValueAt(1, j);
                
            }
        }
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    private String getGeom(double spaz_in, double spaz, double scoppio, int ch) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
    
    private static class MyTableModel extends AbstractTableModel {

        private List<Data> dataList = new ArrayList<Data>();
        private List<String> colname = new ArrayList<String>();
        double spaz_in, spaz;
        String[] module;
        JComboBox jComboBox3;
        String geom = "";
        int ch;

        private String getGeom(double spaz_in, double spaz, double scoppio, int ch) {


            if (scoppio < spaz_in) {
                return "" + (scoppio - spaz_in) + "m";
            } else if (scoppio >= spaz_in && scoppio <= (spaz_in + ((ch - 1) * spaz))) {
                return "" + ((scoppio - spaz_in) / spaz);
            } else if (scoppio > (spaz_in + ((ch - 1) * spaz))) {
                return "+" + (scoppio - (spaz_in + ((ch - 1) * spaz))) + "m";
            }
            return "";

        }

        public int getColumnCount() {
            return ch;
        }

        public void addData(Data data) {
            dataList.add(data);
            
            fireTableRowsInserted(dataList.size() - 1, dataList.size() - 1);
        }

        public int getRowCount() {
            return dataList.size();
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            Data data = dataList.get(rowIndex);
            try{
                return data.x[columnIndex];
            }
            catch(Exception ex){
                return "Error";
            }
            
        }

         @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            Data data = dataList.get(rowIndex);
            /*if (columnIndex == 0) {
                data.data1 = (String) aValue;
            } else {
                data.data2 = (String) aValue;
            }
            */
            data.x[columnIndex]=Double.parseDouble((String) aValue);
            
            geom = "";
       /*     for (int i = 0; i < dataList.size(); i++) {
               geom=geom+" "+ this.getGeom(spaz_in, spaz, Double.parseDouble(((Data) dataList.get(i)).data2), ch);
            }
*/


            //module[0] = geom;
            //jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(module));
            this.fireTableCellUpdated(rowIndex, columnIndex);
            //return columnIndex == 0 ? data.data1 : data.data2;
        }

        public String getColumnName(int pCol) {
            colname.clear();
            for(int i=0;i<ch;i++){
                colname.add("G"+(i+1));
            }
            
            return colname.get(pCol);
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            //Note that the data/cell address is constant,
            //no matter where the cell appears onscreen.
            if (row < 1) {
                return false;
            } else {
                return true;
            }
        }

        private void setGeom(String s, String[] mod, JComboBox jCombo) {
            geom = s;
            jComboBox3 = jCombo;
            module = mod;
        }
        
        
    }

    private static class Data {

        public String data1;
        public String data2;
        public double[] x;
       // public double[] z;
        
        public Data(int n){
            x=new double[n];
            for(int i=0;i<n;i++) x[i]=i;
        }

        public Data(String data1, String data2) {
            this.data1 = data1;
            this.data2 = data2;
        }
    }

    class MyTableModelListener implements TableModelListener {

        JTable table;

        MyTableModelListener(JTable table) {
            this.table = table;
        }

        @Override
        public void tableChanged(TableModelEvent e) {
            int firstRow = e.getFirstRow();
            int lastRow = e.getLastRow();
            int index = e.getColumn();

            switch (e.getType()) {
                case TableModelEvent.INSERT:
                    for (int i = firstRow; i <= lastRow; i++) {
                        System.out.println(i);
                    }
                    break;
                case TableModelEvent.UPDATE:
                    if (firstRow == TableModelEvent.HEADER_ROW) {
                        if (index == TableModelEvent.ALL_COLUMNS) {
                            System.out.println("A column was added");
                        } else {
                            System.out.println(index + "in header changed");
                        }
                    } else {
                        for (int i = firstRow; i <= lastRow; i++) {
                            if (index == TableModelEvent.ALL_COLUMNS) {
                                System.out.println("All columns have changed");
                            } else {


                                System.out.println(index);
                            }
                        }
                    }
                    break;
                case TableModelEvent.DELETE:
                    for (int i = firstRow; i <= lastRow; i++) {
                        System.out.println(i);
                    }
                    break;
            }
        }
    }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
