/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.myeditor;

//import com.sun.xml.internal.ws.util.xml.CDATA;
import it.vs30.smartRefract.utils.Bool;
import it.vs30.smartRefract.utils.FB_set;
import it.vs30.smartRefract.utils.JShot;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import org.myorg.myapi.FirstBrake;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;

/**
 * Class representing a view for phantoming. Extends JPanel and contains various
 * methods for drawing graphs.
 *
 * @author PC
 */
public class JPhantoming_view extends javax.swing.JPanel {

    // Seismic data
    protected Indagine dati_sismici = null;
    // Array of colors
    protected Color[] color = null;
    // Array of phantoming visibility
    protected Bool[] phnt_visible = null;
    // Array of base shots
    protected int[] base_shot = null;
    // Flags for drawing forward and reverse base shots
    public boolean drawForwardBS = false, drawReverseBS = false;
    // Edit index
    private int edit_index;
    // Edit flag
    private boolean edit;
    // List of shots
    private ArrayList<Integer> shots = null;
    // List of JShot
    private ArrayList<JShot> shs;
    // Array of manual phantoming visibility
    protected Bool[] man_phant_visible = null;

    /**
     * Default constructor.
     */
    public JPhantoming_view() {
        initComponents();

    }

    public JPhantoming_view(Indagine proj, Color[] color, Bool[] phnt_visible) {
        initComponents();
        dati_sismici = proj;
        this.color = color;
        this.phnt_visible = phnt_visible;
    }

    public JPhantoming_view(Indagine proj, Color[] color, Bool[] phnt_visible, int[] base_shot) {
        initComponents();
        dati_sismici = proj;
        this.color = color;
        this.phnt_visible = phnt_visible;
        this.base_shot = base_shot;
    }

    public JPhantoming_view(Indagine proj, Color[] color, Bool[] phnt_visible, Bool[] man_phnt_visible) {
        initComponents();
        dati_sismici = proj;
        this.color = color;
        this.phnt_visible = phnt_visible;
        this.man_phant_visible = man_phnt_visible;
    }

    public JPhantoming_view(Indagine proj, Color[] color, Bool[] phnt_visible, Bool[] man_phnt_visible, int[] base_shot) {
        initComponents();
        dati_sismici = proj;
        this.color = color;
        this.phnt_visible = phnt_visible;
        this.man_phant_visible = man_phnt_visible;
        this.base_shot = base_shot;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Method to get the maximum value from an array of doubles.
     *
     * @param list Array of doubles
     * @return Maximum value
     */
    double get_MAX(double[] list) {
        double max = 0.0;
        get_MAX(list, max);
        return max;

    }

    double get_MAX(FirstBrake[] list, double old_max) {
        double max = old_max;
        for (int i = 0; i < list.length; i++) {
            if (list[i] != null) {
                if (max < list[i].time) {
                    max = list[i].time;
                }
            }
        }

        return max;

    }

    double get_MAX(FirstBrake[] list) {
        double max = 0.0;
        get_MAX(list, max);
        return max;

    }

    double get_MAX(double[] list, double old_max) {
        double max = old_max;
        for (int i = 0; i < list.length; i++) {
            if (max < list[i]) {
                max = list[i];
            }
        }

        return max;

    }

    /**
     * Method to draw the graphical components.
     *
     * @param g Graphics object
     */
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.BLACK);
        double max = 0.0;
        // Calculate the maximum value for the seismic data
        for (int i = 0; i < dati_sismici.VfB_A.length - 1; i++) {
            max = this.get_MAX(dati_sismici.VfB_A[i].fb, max);

        }
        for (int i = 0; i < dati_sismici.VfB_R.length - 1; i++) {
            max = this.get_MAX(dati_sismici.VfB_R[i].fb, max);

        }
        max = 1.2 * max;
        // Draw the axes and ticks
        this.drawAssi(g, 0, max);
        this.draw_Y_tick(g, 0, max);
        // Draw the edit shots if necessary
        if (shots != null && this.edit) {
            draw_edit_shot(g, 0, max);
        }
        // Draw the forward and reverse base shots if necessary
        if (this.drawForwardBS) {
            this.draw_Punti(g, 0, max, ((FirstBrakeList) dati_sismici.stesa.get(base_shot[0])).fb, new Color(150, 200, 200), true);
        }
        if (this.drawReverseBS) {
            this.draw_Punti(g, 0, max, ((FirstBrakeList) dati_sismici.stesa.get(base_shot[1])).fb, new Color(150, 200, 200), true);
        }

        // Draw the points for the seismic data
        this.draw_Punti(g, 0, max, dati_sismici.VfB_A, color);
        this.draw_Punti(g, 0, max, dati_sismici.VfB_R, color);

        // Try to draw the manual phantoming
        this.tryToDrawManPhantoming(g, max);

    }

    /**
     * Method to draw the axes.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     */
    public void drawAssi(Graphics g, double min, double max) {
        int w = this.getWidth();
        int h = this.getHeight();
        g.drawRect(30, 35, w - 60, h - 60);

    }

    /**
     * Method to set the project.
     *
     * @param proj Indagine object
     */
    void setProj(Indagine proj) {
        dati_sismici = proj;

    }

   
    /**
     * Draws Y-axis tick marks and labels on the given Graphics context.
     *
     * @param g    the Graphics context to draw on
     * @param min  the minimum value for the Y-axis (currently unused)
     * @param max  the maximum value for the Y-axis
     *
     * This method calculates the step size for the Y-axis ticks based on the height of the component
     * and the maximum value. It then draws major and minor tick marks at appropriate intervals along
     * the Y-axis, as well as labels for the major tick marks. The size and spacing of the tick marks
     * and labels are adjusted based on the width of the component.
     */
    private void draw_Y_tick(Graphics g, int min, double max) {

        int w = this.getWidth();
        int h = this.getHeight();
        double xshf = 30;
        int xmax = w;
        int ymax = h;
        double margUp = 30;
        //double ystp = (ymax - (2 * margUp * ymax)) / max;
        int minTic = 0;
        int majTic = 2;
        Graphics2D g2 = (Graphics2D) g.create();

        double ystp = (h - 60) / max;

        if (max / 10.0 < 1) {
            majTic = 2;
            minTic = 1;

        } else if (max / 10.0 < 2) {
            majTic = 3;
            minTic = 1;
        } else if (max / 10.0 < 4) {
            majTic = 5;
            minTic = 2;
        } else if (max / 10.0 < 10) {
            majTic = 10;
            minTic = 5;
        } else if (max / 10.0 < 30) {
            majTic = 20;
            minTic = 10;
        }

        g2.setFont(new Font("Dialog", Font.PLAIN, (int) (12 * (w / 1000.0))));
        FontMetrics fontMetrics = g2.getFontMetrics();

        int height = fontMetrics.getHeight();

        //FontMetrics fontMetrics = g2.getFontMetrics();
        for (int i = 0; i < max; i = i + minTic) {
            if (i % majTic == 0) {
                g2.drawLine((int) (xshf ), ymax - (int) (i * ystp + (margUp)), (int) (xshf * 0.8), ymax - (int) (i * ystp + (margUp)));
                int width = fontMetrics.stringWidth("" + (i));

                g2.drawString("" + (i), (int) (xshf * 0.75) - width, ymax - (int) (i * ystp + (margUp) - (height / 3)));
                g2.drawLine((int) (xmax - xshf ), ymax - (int) (i * ystp + (margUp)), (int) (xmax - xshf * 0.8), ymax - (int) (i * ystp + (margUp)));

            } else {
                g2.drawLine((int) (xshf * 0.9), ymax - (int) (i * ystp + (margUp)), (int) (xshf ), ymax - (int) (i * ystp + (margUp)));
                g2.drawLine((int) (xmax - xshf), ymax - (int) (i * ystp + (margUp)), (int) (xmax - xshf * 0.9), ymax - (int) (i * ystp + (margUp)));
            }
        }

    }

    /**
     * Method to draw the points for the seismic data.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     * @param firstBrakeList Array of FirstBrakeList
     * @param color Array of colors
     */
    private void draw_Punti(Graphics g, int min, double max, FirstBrakeList[] firstBrakeList, Color[] color) {
        int w = this.getWidth();
        int h = this.getHeight();
        int xshf = 30;
        int xmax = w;
        int ymax = h;
        double margUp = 30;
        int nch = firstBrakeList[1].fb.length;

        double x_step = (w - (2 * xshf)) / nch;
        double ystp;
        ystp = (h - 60) / max;

        try {
            for (int i = 1; i < firstBrakeList.length; i++) {
                if (this.phnt_visible[i].getValue()) {
                    for (int j = 0; j < firstBrakeList[i].fb.length; j++) {
                        g.setColor(color[i]);
                        g.drawRect(xshf + (int) ((j + 1) * x_step) - 2, ymax - (int) (firstBrakeList[i].fb[j].time * ystp + (margUp)) - 2, 4, 4);
                        if (j > 0) {
                            Graphics2D g2d = (Graphics2D) g.create();
                            float[] dashPattern = {5, 5};
                            g2d.setColor(color[i]);
                            g2d.setStroke(new java.awt.BasicStroke(1, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER, 10, dashPattern, 0));
                            g2d.drawLine(
                                    xshf + (int) ((j) * x_step), ymax - (int) (firstBrakeList[i].fb[j - 1].time * ystp + (margUp)),
                                    xshf + (int) ((j + 1) * x_step), ymax - (int) (firstBrakeList[i].fb[j].time * ystp + (margUp))
                            );
                            g2d.dispose();
                        }

                        g.setColor(Color.orange);
                        g.drawLine(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (firstBrakeList[i].fb[j].time * ystp + (margUp)) - 3, xshf + (int) ((j + 1) * x_step) + 3, ymax - (int) (firstBrakeList[i].fb[j].time * ystp + (margUp)) + 3);
                        g.drawLine(xshf + (int) ((j + 1) * x_step) + 3, ymax - (int) (firstBrakeList[i].fb[j].time * ystp + (margUp)) - 3, xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (firstBrakeList[i].fb[j].time * ystp + (margUp)) + 3);

                    }
                }
            }
        } catch (Exception ex) {
        }

    }

    /**
     * Method to draw the points for the seismic data.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     * @param fb Array of FirstBrake
     * @param color Color
     */
    private void draw_Punti(Graphics g, int min, double max, FirstBrake[] fb, Color color) {
        int w = this.getWidth();
        int h = this.getHeight();
        int xshf = 30;

        int ymax = h;
        double margUp = 30;
        int nch = fb.length;
        int x_step = (int) ((w - (2 * xshf)) / nch);
        double ystp = (h - 60) / max;

        try {

            for (int j = 0; j < fb.length; j++) {
                g.setColor(color);
                if (this.edit) {
                    if (fb[j].layer == this.edit_index) {
                        g.drawRect(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (fb[j].time * ystp + (margUp)) - 3, 6, 6);
                    }
                } else {
                    g.drawRect(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (fb[j].time * ystp + (margUp)) - 3, 6, 6);
                }
            }

        } catch (Exception ex) {
        }

    }

    /**
     * Method to draw the points for the seismic data.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     * @param fb Array of FirstBrake
     * @param shift Shift value
     * @param color Color
     * @param lungh_strum Length of the instrument
     */
    private void draw_Punti(Graphics g, int min, double max, FirstBrake[] fb, double shift, Color color, double lungh_strum) {
        int w = this.getWidth();
        int h = this.getHeight();
        int xshf = 30;
        int xmax = w;
        int ymax = h;
        double margUp = 30;
        int nch = dati_sismici.stesa.get(0).ch;
        //fb.length;
        int x_step = (int) ((w - (2 * xshf)) / nch);
        double ystp = (h - 60) / max;
        int x_shift = (int) (x_step * this.dati_sismici.stesa.get(0).spaz);
        //double spaz_in=this.dati_sismici.stesa.get(0).spaz_in;

        try {

            for (int j = 0; j < fb.length; j++) {
                g.setColor(color);
                if (this.edit) {
                    if (fb[j].layer == this.edit_index) {
                        g.drawRect(xshf + (int) ((fb[j].chan + 1) * x_step) - 3, ymax - (int) ((fb[j].time + shift) * ystp + (margUp)) - 3, 6, 6);
                        if (j > 0) {
                            Graphics2D g2d = (Graphics2D) g.create();
                            float[] dashPattern = {5, 2};
                            g2d.setColor(color);
                            g2d.setStroke(new java.awt.BasicStroke(1, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER, 10, dashPattern, 0));
                            g2d.drawLine(
                                    xshf + (int) ((fb[j-1].chan + 1) * x_step), ymax - (int) ((fb[j - 1].time + shift) * ystp + (margUp)),
                                    xshf + (int) ((fb[j].chan + 1) * x_step), ymax - (int) ((fb[j].time +shift) * ystp + (margUp))
                            );
                            g2d.dispose();
                        }
                        //g.drawRect(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (fb[j].time * ystp + (margUp)) - 3, 6, 6);
                    }
                } else {
                    //g.drawRect(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (fb[j].time * ystp + (margUp)) - 3, 6, 6);
                }
            }

        } catch (Exception ex) {
        }

    }

    /**
     * Method to draw the points for the seismic data.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     * @param fb Array of FirstBrake
     * @param color Color
     * @param filled Filled flag
     */
    private void draw_Punti(Graphics g, int min, double max, FirstBrake[] fb, Color color, boolean filled) {
        if (!filled) {
            draw_Punti(g, min, max, fb, color);
        } else {
            int w = this.getWidth();
            int h = this.getHeight();
            int xshf = 30;
            int xmax = w;
            int ymax = h;
            double margUp = 30;
            int nch = fb.length;
            double x_step = (w - (2 * xshf)) / nch;
            double ystp = (h - 60) / max;
            try {

                for (int j = 0; j < fb.length; j++) {
                    g.setColor(color);
                    if (this.edit) {
                        if (fb[j].layer == this.edit_index) {
                            g.fillRect(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (fb[j].time * ystp + (margUp)) - 3, 6, 6);
                        }
                    } else {
                        g.fillRect(xshf + (int) ((j + 1) * x_step) - 3, ymax - (int) (fb[j].time * ystp + (margUp)) - 3, 6, 6);
                    }
                }

            } catch (Exception ex) {
            }
        }

    }

    /**
     * Method to set the edit layer.
     *
     * @param self_index Layer index
     * @param edit Edit flag
     * @param shots List of shots
     * @param shs List of JShot
     */
    void setEditLayer(int self_index, boolean edit, ArrayList<Integer> shots, ArrayList<JShot> shs) {
        this.edit_index = self_index;
        this.edit = edit;
        this.shots = shots;
        this.shs = shs;
        this.invalidate();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Method to draw the edit shots.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     */
    private void draw_edit_shot(Graphics g, int min, double max) {
        int i = 0;
        for (JShot shot : dati_sismici.shots) {
            i++;

            for (FB_set fbs : shot.FB_sets) {
                if (fbs.layer == (edit_index) && fbs.visible) {
                    this.draw_Punti(g, min, max, (fbs.fb.toArray(new FirstBrake[fbs.fb.size()])), fbs.shift, color[254 - i], (dati_sismici.stesa.get(0).spaz * (dati_sismici.stesa.get(0).ch)));
                    //break;
                }
            }
        }

        /*
         for (Integer i : shots) {

         this.draw_Punti(g, min, max, ((FirstBrakeList) dati_sismici.stesa.get(i)).fb, color[254 - i]);
         }*/
    }

    /**
     * Method to try to draw the manual phantoming.
     *
     * @param g Graphics object
     * @param max Maximum value
     */
    private void tryToDrawManPhantoming(Graphics g, double max) {
        for (int i = 1; i < this.man_phant_visible.length; i++) {
            if (man_phant_visible[i].getValue()) {
                this.draw_Circle(g, 0, max, dati_sismici.man_Phant_and[i - 1].fb, Color.black);
                this.draw_Circle(g, 0, max, dati_sismici.man_Phant_rit[i - 1].fb, Color.black);

            }
        }

        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Method to draw circles for the seismic data.
     *
     * @param g Graphics object
     * @param min Minimum value
     * @param max Maximum value
     * @param fb Array of FirstBrake
     * @param color Color
     */
    private void draw_Circle(Graphics g, int min, double max, FirstBrake[] fb, Color color) {
        int w = this.getWidth();
        int h = this.getHeight();
        int xshf = 30;
        int xmax = w;
        int ymax = h;
        double margUp = 30;
        int nch = fb.length;
        int x_step = (int) ((w - (2 * xshf)) / nch);
        double ystp = (h - 60) / max;

        try {

            for (int j = 0; j < fb.length; j++) {
                g.setColor(color);
                if (false) { //this.edit
                    if (fb[j].layer == this.edit_index) {
                        g.drawOval(xshf + (int) ((j + 1) * x_step) - 4, ymax - (int) (fb[j].time * ystp + (margUp)) - 4, 8, 8);
                    }
                } else {
                    g.drawOval(xshf + (int) ((j + 1) * x_step) - 4, ymax - (int) (fb[j].time * ystp + (margUp)) - 4, 8, 8);
                }
            }

        } catch (Exception ex) {
        }

    }
}
