/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JSelStrato_dlg.java
 *
 * Created on 2-set-2011, 0.02.19
 */
package it.vs30.myeditor;

//import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;
import org.myorg.myviewer.MyViewerTopComponent;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 *
 * @author user
 */
public class JSelStrato_dlg extends javax.swing.JDialog {

    public int inizio, fine;
    public double velocita;
    private double a;
    private double b;
    private int indj;
   // public JDromoView dv;

    /**
     * Creates new form JSelStrato_dlg
     */
    public JSelStrato_dlg() {
        //super(parent, modal);
        setUndecorated(true);
        initComponents();
    }

    public void update() {
    }

    public void setProj(Indagine proj) {
        this.proj = proj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(57, 112, 70));
        jButton1.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(70, 93, 120));
        jButton2.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(131, 74, 37));
        jButton5.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(org.openide.util.NbBundle.getMessage(JSelStrato_dlg.class, "JSelStrato_dlg.jButton8.text")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(indj);
        double scoppio = ((fbl.scoppio - fbl.spaz_in) / fbl.spaz);
        if (((FirstBrakeList) proj.stesa.get(indj)).spaz_in + (((FirstBrakeList) proj.stesa.get(indj)).spaz * (inizio)) > ((FirstBrakeList) proj.stesa.get(indj)).scoppio) {
            ((FirstBrakeList) proj.stesa.get(indj)).setLayertoZero();
          //  ((FirstBrakeList) proj.stesa.get(indj)).updateLayer(1,inizio,fine);
            ((FirstBrakeList) proj.stesa.get(indj)).strato1 = inizio + "-" + fine;
            proj.setdromo();
            ((FirstBrakeList) proj.stesa.get(indj)).setLayertoZero();
            ((FirstBrakeList) proj.stesa.get(indj)).setLayer(inizio, fine, 1);
            ((FirstBrakeList) proj.stesa.get(indj)).intersect();
            proj.buildShots();
            proj.buildDromocrone();
            ((FirstBrakeList) proj.stesa.get(indj)).dromo[0].b = b;
            ((FirstBrakeList) proj.stesa.get(indj)).dromo[0].a = a;
        } else {
            ((FirstBrakeList) proj.stesa.get(indj)).setLayertoZero();
            ((FirstBrakeList) proj.stesa.get(indj)).strato1R = inizio + "-" + fine;
            proj.setdromo();
            ((FirstBrakeList) proj.stesa.get(indj)).setLayer(inizio, fine, 1);
            ((FirstBrakeList) proj.stesa.get(indj)).intersect();
            proj.buildShots();
            proj.buildDromocrone();

            ((FirstBrakeList) proj.stesa.get(indj)).dromoR[0].b = b;
            ((FirstBrakeList) proj.stesa.get(indj)).dromoR[0].a = a;


        }
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(indj);
        double scoppio = ((fbl.scoppio - fbl.spaz_in) / fbl.spaz);
        if (((FirstBrakeList) proj.stesa.get(indj)).spaz_in + (((FirstBrakeList) proj.stesa.get(indj)).spaz * (inizio)) > ((FirstBrakeList) proj.stesa.get(indj)).scoppio) {
            ((FirstBrakeList) proj.stesa.get(indj)).setLayertoZero();
            ((FirstBrakeList) proj.stesa.get(indj)).strato2 = inizio + "-" + fine;
            proj.setdromo();
            ((FirstBrakeList) proj.stesa.get(indj)).setLayer(inizio, fine, 2);
            ((FirstBrakeList) proj.stesa.get(indj)).intersect();
            proj.buildShots();
            proj.buildDromocrone();

            ((FirstBrakeList) proj.stesa.get(indj)).dromo[1].b = b;
            ((FirstBrakeList) proj.stesa.get(indj)).dromo[1].a = a;
        } else {
            ((FirstBrakeList) proj.stesa.get(indj)).setLayertoZero();
            ((FirstBrakeList) proj.stesa.get(indj)).strato2R = inizio + "-" + fine;
            proj.setdromo();
            ((FirstBrakeList) proj.stesa.get(indj)).setLayer(inizio, fine, 2);
            ((FirstBrakeList) proj.stesa.get(indj)).intersect();
            proj.buildShots();
            proj.buildDromocrone();

            ((FirstBrakeList) proj.stesa.get(indj)).dromoR[1].b = b;
            ((FirstBrakeList) proj.stesa.get(indj)).dromoR[1].a = a;


        }
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FileOutputStream fos = null;
        this.hide();
        String userHome = "user.home";

        // We get the path by getting the system property with the 
        // defined key above.
        String path = System.getProperty(userHome);

        try {
            fos = new FileOutputStream(path + "/smartRefract-data/dromo.txt",false);
            OutputStreamWriter os = new OutputStreamWriter(fos);
            os.flush();
            os.close();
        } catch (IOException ex) {
            //  Logger.getLogger(JRefractionView.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fos.close();
            } catch (IOException ex) {
                //    Logger.getLogger(JRefractionView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        proj.setdromo();

        proj.sezDT(true);

        // proj.phantom(1);


    }//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(indj);
    double scoppio = ((fbl.scoppio - fbl.spaz_in) / fbl.spaz);
    if (( proj.stesa.get(indj)).spaz_in + (((FirstBrakeList) proj.stesa.get(indj)).spaz * (inizio)) > ((FirstBrakeList) proj.stesa.get(indj)).scoppio) {
        ( proj.stesa.get(indj)).setLayertoZero();
        ( proj.stesa.get(indj)).strato3 = inizio + "-" + fine;
        proj.setdromo();
        ( proj.stesa.get(indj)).setLayer(inizio, fine, 3);
        //   ((FirstBrakeList) proj.stesa.get(indj)).intersect();
        proj.buildShots();
        proj.buildDromocrone();

        ( proj.stesa.get(indj)).dromo[2].b = b;
        ( proj.stesa.get(indj)).dromo[2].a = a;
    } else {
        ( proj.stesa.get(indj)).strato3R = inizio + "-" + fine;
        ( proj.stesa.get(indj)).setLayertoZero();
        ( proj.stesa.get(indj)).setLayer(inizio, fine, 3);

        proj.setdromo();
        //  ((FirstBrakeList) proj.stesa.get(indj)).intersect();
        proj.buildShots();
        proj.buildDromocrone();

        ( proj.stesa.get(indj)).dromoR[2].b = b;
        ( proj.stesa.get(indj)).dromoR[2].a = a;


    }
    this.hide();
}//GEN-LAST:event_jButton5ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
       // AWTUtilities.setWindowOpacity(this, 1f);
    }//GEN-LAST:event_formMouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   /*     // TODO add your handling code here:
        dv.VAR++;
        if (dv.VAR > 2) {
            dv.VAR = 0;
        }

        switch (dv.VAR) {
            case 0:
                //dv.VAR=1;
                dv.andata = true;
                dv.ritorno = true;
                break;
            case 1:
                //dv.VAR=2;
                dv.andata = true;
                dv.ritorno = false;
                break;
            case 2:
                //dv.VAR=2;
                dv.andata = false;
                dv.ritorno = true;
                break;
        }
        this.setVisible(false);


        // dv.andata=!dv.andata;




        //this.setVisible(false);
        dv.repaint();
*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
  /*      dv.is_white = !dv.is_white;
        dv.obj.is_white = dv.is_white;
        if (dv.is_white) {
            dv.setBackground(Color.WHITE);
            jButton7.setText("Black background");
        } else {
            dv.setBackground(Color.BLACK);
            jButton7.setText("White background");
        }
        this.setVisible(false);
        //Tv.undo();
        dv.repaint();
        TopComponent tc = WindowManager.getDefault().findTopComponent("MyViewerTopComponent");
        Lookup tcLookup = tc.getLookup();
        ((MyViewerTopComponent) tc).gmview.is_white = dv.is_white;
        ((MyViewerTopComponent) tc).gmview.invalidate();
        ((MyViewerTopComponent) tc).gmview.repaint();

*/

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        /*MyEditor editor = new MyEditor();
         editor.open();
         editor.requestActive();*/
        fc.setFileFilter(new PNGFileFilter());
        fc.setMultiSelectionEnabled(true);
        this.setVisible(false);

        //      proj.checkLic();
        if (/*proj.licenza*/true) {
            int returnVal = fc.showSaveDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                BufferedImage im_s = new BufferedImage(1400, 1000, BufferedImage.TYPE_INT_RGB);   //    (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

                Graphics offg = im_s.getGraphics();
                Graphics2D g2 = (Graphics2D) offg.create();
     /*           if (dv.is_white) {
                    g2.setBackground(Color.white);
                    g2.clearRect(0, 0, 1400, 1000);
                } else {
                    g2.setBackground(Color.BLACK);
                    g2.clearRect(0, 0, 1400, 1000);
                }

                dv.drawDr(offg, 1400, 1000, true);
                //dv.drawSezione(offg, 2000, 1450);
*/
                try {
                    // retrieve image

                    File outputfile = fc.getSelectedFile();

                    if (!outputfile.getPath().toLowerCase().endsWith(".png")) {
                        outputfile = new File(outputfile.getPath() + ".png");
                    }
                    ImageIO.write(im_s, "png", outputfile);
                } catch (IOException e) {
                }
            }

        }

        // sV.repaint();


    }

    /**
     * @param args the command line arguments
     */
    class PNGFileFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File f) {
            return f.isDirectory() || f.getName().toLowerCase().endsWith(".png");
        }

        @Override
        public String getDescription() {
            return "PNG image file";
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    /**
     * @param args the command line arguments
     */
    Indagine proj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables

    void setAB(double a, double b) {
        this.a = a;
        this.b = b;
    }

    public void setIndj(int indj) {
        this.indj = indj;
    }
}
