/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * jTavolozzaDlg.java
 *
 * Created on 8-mar-2012, 21.41.52
 */
package it.vs30.myeditor;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.JColorChooser;

/**
 *
 * @author pitta1981
 */
public class jTavolozzaDlg extends javax.swing.JDialog {

    /**
     * Creates new form jTavolozzaDlg
     */
    public jTavo_draw tavDr;
    JSezioneView sV;
    private String selezionato;
    private String[] stile = new String[20];
    private final boolean[][][] cell = new boolean[20][15][15];

    public jTavolozzaDlg(JSezioneView sv) {
        //super(parent, modal);
        initComponents();
        sV = sv;
        tavDr = new jTavo_draw();

        String[] strato = {"Strato 1", "Strato 2", "Strato 3"};
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(strato));
        String userHome = "user.home";

        // We get the path by getting the system property with the 
        // defined key above. 
        String path = System.getProperty(userHome);

        try (FileInputStream fis = new FileInputStream(path + "/smartRefract-data/" + "brush.config");
             InputStreamReader isr = new InputStreamReader(fis);
             BufferedReader br = new BufferedReader(isr)) {
            int i = 0;
            String linea = br.readLine();
            // String[] module = new String[20];
            while (linea != null && i < 20) {
                stile[i] = linea;

                linea = br.readLine();
                for (int k = 0; k < 15; k++) {
                    for (int j = 0; j < 15; j++) {
                        cell[i][k][j] = (linea.charAt(j + (15 * k)) == '0' ? false : true);
                    }
                }
                i++;
                linea = br.readLine();

            }
            //int n=Integer.parseInt(linea);

            //  jpWave.setStatus(statusMessageLabel);
            //jpWave.newSignal(16);
            //jpWave.sample[1]=new ArrayList();
            //linea = br.readLine();
            int chanel = Integer.parseInt(linea);

        } catch (Exception e1) {
            System.out.println("Geometry shot config file " + e1.getMessage());

        }

        jList1.setModel(new javax.swing.DefaultComboBoxModel(stile));
        jList1.setSelectedIndex(0);
        tavDr.cell = this.cell[0];

        jButton4.setEnabled(checkbox1.getState());
        jPanel1.setSize(150, 150);
        jPanel1.add(tavDr);
    }

    public jTavolozzaDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        jComboBox1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton2.text")); // NOI18N

        jPanel1.setMaximumSize(new java.awt.Dimension(150, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jTextField1.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jTextField1.text")); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton3.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.setForeground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        checkbox1.setLabel(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.checkbox1.label")); // NOI18N
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(org.openide.util.NbBundle.getMessage(jTavolozzaDlg.class, "jTavolozzaDlg.jButton7.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton7)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n_strato = jComboBox1.getSelectedIndex();

        this.drawFilling(n_strato);

        this.setVisible(false);
        String userHome = "user.home";

        // We get the path by getting the system property with the 
        // defined key above. 
        String path = System.getProperty(userHome);

        try {
            FileOutputStream fos = new FileOutputStream(path + "/smartRefract-data/" + "brush.config", false);

            OutputStreamWriter os = new OutputStreamWriter(fos);
            /*//selezionato = (String) jComboBox3.getSelectedItem();
            selezionato = this.jTextField1.getText();
            boolean esiste = false;
            for (int i = 0; i < 20; i++) {
            if (selezionato.equals(this.stile[i])) {
            esiste = true;
            }
            }
            if (!esiste) {
            os.write(selezionato + "\n");
            for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
            os.write((this.tavDr.cell[i][j] ? 1 : 0) + "");
            }
            }
            os.write("\n");
            }*/
            for (int k = 0; k < 20; k++) {
                if (stile[k] != null) {
                    os.write(stile[k] + "\n");
                    for (int i = 0; i < 15; i++) {
                        for (int j = 0; j < 15; j++) {
                            os.write((this.cell[k][i][j] ? 1 : 0) + "");
                        }
                    }
                    os.write("\n");
                }
            }

            //              os.write(fl.spaz + "\n");
            os.flush();
            os.close();

        } catch (Exception e1) {
            System.out.println("Geometry shot config file OK" + e1.getMessage());

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        jTextField1.setText("" + jList1.getSelectedValue());
        try {
            tavDr.cell = cell[jList1.getSelectedIndex()];
        } catch (Exception e1) {
            System.out.println("Campitura " + e1.getMessage());

        }

        tavDr.invalidate();
        tavDr.repaint();

    }//GEN-LAST:event_jList1ValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        tavDr.newBColor = JColorChooser.showDialog(
                this,
                "Choose Background Color",
                jPanel2.getBackground());
        jPanel3.setBackground(tavDr.newBColor);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tavDr.newFColor = JColorChooser.showDialog(
                this,
                "Choose Background Color",
                jPanel2.getBackground());
        jPanel2.setBackground(tavDr.newFColor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        // TODO add your handling code here:
        jButton4.setEnabled(checkbox1.getState());
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        int n_strato = jComboBox1.getSelectedIndex();

        String userHome = "user.home";

        // We get the path by getting the system property with the 
        // defined key above. 
        String path = System.getProperty(userHome);

        this.drawFilling(n_strato);

        //this.setVisible(false);
        try {
            FileOutputStream fos = new FileOutputStream(path + "/smartRefract-data/" + "brush.config", false);

            OutputStreamWriter os = new OutputStreamWriter(fos);
            //selezionato = (String) jComboBox3.getSelectedItem();
            selezionato = this.jTextField1.getText();
            boolean esiste = false;
            for (int i = 0; i < 20; i++) {
                if (selezionato.equals(this.stile[i])) {
                    esiste = true;
                }
            }
            if (!esiste) {
                os.write(selezionato + "\n");
                for (int i = 0; i < 15; i++) {
                    for (int j = 0; j < 15; j++) {
                        os.write((this.tavDr.cell[i][j] ? 1 : 0) + "");
                    }
                }
                os.write("\n");
            }

            //              os.write(fl.spaz + "\n");
            os.flush();
            os.close();

        } catch (Exception e1) {
            System.out.println("Geometry shot config file " + e1.getMessage());

        }
        this.Apply_Tav();


    }//GEN-LAST:event_jButton5ActionPerformed

    void Apply_Tav() {
        if (this.tavDr.im[0] != null) {
            sV.bIm1 = this.tavDr.im[0];
            sV.dAPI.bIm1 = this.tavDr.im[0];
        }

        if (this.tavDr.im[1] != null) {
            sV.bIm2 = this.tavDr.im[1];
            sV.dAPI.bIm2 = this.tavDr.im[1];
        }

        if (this.tavDr.im[2] != null) {
            sV.bIm3 = this.tavDr.im[2];
            sV.dAPI.bIm3 = this.tavDr.im[2];
        }

        sV.repaint();

        // sV.invalidate();
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        selezionato = this.jTextField1.getText();
        boolean esiste = false;
        for (int i = 0; i < 20; i++) {
            if (selezionato.equals(this.stile[i])) {
                esiste = true;
            }
        }
        if (!esiste) {
            int k = 0;
            while (stile[k] != null && k < 19) {

                k++;
            }
            this.stile[k] = selezionato;
            this.cell[k] = this.tavDr.cell;

        }
        jList1.setModel(new javax.swing.DefaultComboBoxModel(stile));
        jList1.setSelectedIndex(0);
        tavDr.cell = this.cell[0];
        tavDr.invalidate();
        tavDr.repaint();


    }//GEN-LAST:event_jButton6ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void drawFilling(int n) {
        tavDr.im[n] = new BufferedImage(14, 14, BufferedImage.TYPE_INT_RGB);//(BufferedImage) this.createImage(14, 14);

        Graphics offg = tavDr.im[n].getGraphics();

        Graphics2D g2 = (Graphics2D) offg.create();
        if (checkbox1.getState()) {
            g2.setBackground(tavDr.newBColor);
        } else {
            g2.setBackground(Color.BLACK);
        }
        g2.clearRect(0, 0, 14, 14);
        //g2.fillRect(0, 0, 14, 14);

        g2.setColor((tavDr.newFColor == Color.BLACK) ? Color.WHITE : tavDr.newFColor);
        for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
                if (tavDr.cell[i][j]) {
                    g2.fillRect(i, j, 1, 1);

                }
            }
        }

    }
}
