/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jTavo_draw.java
 *
 * Created on 8-mar-2012, 21.45.13
 */
package it.vs30.myeditor;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author pitta1981
 */
public class jTavo_draw extends javax.swing.JPanel {

    /** Creates new form jTavo_draw */
    BufferedImage[] im = new BufferedImage[3];
    BufferedImage im_s;
    public boolean[][] cell;
    Color newFColor;
    Color newBColor;

    public jTavo_draw() {
        initComponents();
        cell = new boolean[15][15];
        im_s = (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

        this.setSize(150, 150);
        this.setBackground(Color.white);
    }

    @Override
    public void paintComponent(Graphics g) {


        super.paintComponent(g);
        drawAssi(g);
        drawCell(g);
        //disegnaSegnale(g);
        //disegnaPrimoA(g);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        Graphics g = this.getGraphics();
        im_s = (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

        Graphics offg = im_s.getGraphics();
        super.paintComponent(offg);


        int x = (evt.getX() / 10) * 10;
        int y = (evt.getY() / 10) * 10;
        drawAssi(offg);
        drawCell(offg);
        offg.setColor(Color.red);
        offg.drawRect(x, y, 10, 10);
        g.drawImage(im_s, 0, 0, this);


    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int x = (int) (evt.getX() / 10) * 10;
            int y = (int) (evt.getY() / 10) * 10;
            cell[x / 10][y / 10] = true;//!cell[x / 10][y / 10];
            this.invalidate();
            this.repaint();
        } else {
            int x =  (evt.getX() / 10) * 10;
            int y =  (evt.getY() / 10) * 10;
            cell[x / 10][y / 10] = false;//!cell[x / 10][y / 10];
            this.invalidate();
            this.repaint();
        }


    }//GEN-LAST:event_formMouseClicked
    int xx = 0, yy = 0;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Graphics g = this.getGraphics();
        im_s = (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

        Graphics offg = im_s.getGraphics();
        super.paintComponent(offg);


        int x = (evt.getX() / 10) * 10;
        int y =  (evt.getY() / 10) * 10;


        if (xx != x / 10 || yy != y / 10) {
            cell[x / 10][y / 10] = !cell[x / 10][y / 10];
            xx = x / 10;
            yy = y / 10;
        }

        drawAssi(offg);
        drawCell(offg);
        offg.setColor(Color.red);
        offg.drawRect(x, y, 10, 10);
        g.drawImage(im_s, 0, 0, this);
        this.invalidate();
        this.repaint();



        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void drawCell(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g.setColor(Color.black);
        for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
                if (cell[i][j]) {
                    g2.fillRect(i * 10, j * 10, 10, 10);

                }
            }
        }
    }

    private void drawAssi(Graphics g) {
        g.setColor(Color.black);
        for (int i = 0; i < this.getWidth(); i = i + 10) {
            g.drawLine(i, 0, i, this.getHeight());
        }
        for (int i = 0; i < this.getHeight(); i = i + 10) {
            g.drawLine(0, i, this.getWidth(), i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
