/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JVelocitaDlg.java
 *
 * Created on 5-apr-2012, 19.33.03
 */
package it.vs30.myeditor;

import java.awt.Color;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;

/**
 *
 * @author user
 */
public class JVelocitaDlg extends javax.swing.JDialog {

    /** Creates new form JVelocitaDlg */
    public JVelocitaDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JVelocitaDlg(Indagine proj) {
       
        initComponents();
        double spaz=((FirstBrakeList) proj.stesa.get(0)).spaz;
        double spaz_in=((FirstBrakeList) proj.stesa.get(0)).spaz_in;
        JVelocitaView velView=new JVelocitaView(proj.V1A,proj.V2A,proj.V3A,spaz,spaz_in); 
        velView.setBackground(Color.BLACK);
        jPanel2.add(velView);
        this.invalidate();
        velView.repaint();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
