/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tVdlg.java
 *
 * Created on 1-feb-2012, 22.40.42
 */
package it.vs30.myeditor;

import javax.swing.JComboBox;
import javax.swing.SpinnerNumberModel;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;

/**
 *
 * @author user
 */
public class tVdlg extends javax.swing.JDialog {

    /**
     * Creates new form tVdlg
     */
    private JtV_draw tvdraw;
    Indagine proj;
    int success = 0;

    
    public tVdlg(double[] tv1, double[] tv2, double spaz, Indagine prj) {

        initComponents();
        tvdraw = new JtV_draw(tv1, tv2, spaz);

        for (int i = 0; i < 6; i++) {

            tvdraw.tV1A[i] = prj.DTTv(1, (prj.stesa.get(0)).spaz * i);
            for (int j = 0; j < tvdraw.tV1A[i].length; j++) {
                tvdraw.tV1A[i][j] = tvdraw.tV1A[i][j] + (i * 15);

            }

        }


        //jComboBox1 = new JComboBox();
        javax.swing.DefaultComboBoxModel mod = new javax.swing.DefaultComboBoxModel();
        mod.addElement("1");
        proj = prj;
        //jComboBox1.addItem("1");
        if (tv2 != null) {
            mod.addElement("2");

            for (int i = 0; i < 6; i++) {

                tvdraw.tV2A[i] = prj.DTTv(2, (prj.stesa.get(0)).spaz * i);
                for (int j = 0; j < tvdraw.tV2A[i].length; j++) {
                    tvdraw.tV2A[i][j] = tvdraw.tV2A[i][j] + (i * 15);

                }

            }


        }
        jComboBox1.setEditable(true);
        jComboBox1.setModel(mod);
        //  jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0.5","1","1.25","1.5","1.75","2","2.5","3"}));
        this.tvdraw.tV2 = null;
        SpinnerNumberModel model = new SpinnerNumberModel(0, 0, 5, 1);

        jSpinner1.setModel(model);

        jPanel1.add(tvdraw);
    }

    public tVdlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 342));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(220);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 340));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(220, 340));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 340));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(tVdlg.class, "tVdlg.jLabel1.text")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(tVdlg.class, "tVdlg.jLabel2.text")); // NOI18N

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(tVdlg.class, "tVdlg.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(tVdlg.class, "tVdlg.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(org.openide.util.NbBundle.getMessage(tVdlg.class, "tVdlg.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getItem().equals("1")) {
            jSpinner1.setValue(0);
            this.tvdraw.tV1 = proj.Tv1;
            this.tvdraw.tV2 = null;

        } else if (evt.getItem().equals("2")) {
            jSpinner1.setValue(0);
            proj.Tv2 = proj.DTTv(2, proj.xy2);
            this.tvdraw.tV2 = proj.Tv2;
            this.tvdraw.tV1 = null;
        }
        this.tvdraw.invalidate();
        this.tvdraw.repaint();

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("1")) {
            proj.xy = ((Integer)jSpinner1.getValue())*(proj.stesa.get(0)).spaz;
            proj.Tv1 = proj.DTTv(1, proj.xy);
            this.tvdraw.tV1 = proj.Tv1;
        } else if (jComboBox1.getSelectedItem().equals("2")) {
            proj.xy2 = ((Integer)jSpinner1.getValue())*(proj.stesa.get(0)).spaz;
            proj.Tv2 = proj.DTTv(2, proj.xy2);
            this.tvdraw.tV2 = proj.Tv2;

        }
        

        //   proj.xy2 = (Double) jSpinner1.getValue();
        //   proj.Tv2 = proj.DTTv(2, proj.xy2);
        //   this.tvdraw.tV2 = proj.Tv2;
        this.tvdraw.invalidate();
        this.tvdraw.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("1")) {
            proj.xy = ((Integer)jSpinner1.getValue())*(proj.stesa.get(0)).spaz;
            proj.Tv1 = proj.DTTv(1, proj.xy);
            this.tvdraw.tV1 = proj.Tv1;
        } else if (jComboBox1.getSelectedItem().equals("2")) {
            proj.xy2 = ((Integer)jSpinner1.getValue())*(proj.stesa.get(0)).spaz;
            proj.Tv2 = proj.DTTv(2, proj.xy2);
            this.tvdraw.tV2 = proj.Tv2;

        }

        this.success = 1;
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        System.out.println("Spinner xy: "+jSpinner1.getValue());
        if (jComboBox1.getSelectedItem().equals("1")) {
            tvdraw.sel1=(Integer)jSpinner1.getValue();
        } else if (jComboBox1.getSelectedItem().equals("2")) {
            tvdraw.sel2=(Integer)jSpinner1.getValue();
        
        }

        //   proj.xy2 = (Double) jSpinner1.getValue();
        //   proj.Tv2 = proj.DTTv(2, proj.xy2);
        //   this.tvdraw.tV2 = proj.Tv2;
        this.tvdraw.invalidate();
        this.tvdraw.repaint();
        
        
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.success = 0;
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
