/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.smartUI;

import it.vs30.myeditor.JPhantoming_view;

/**
 *
 * @author PC
 */
public class JCustom_Base_Shot extends javax.swing.JPanel {
    public JPhantoming_view jPhant_view;

    /**
     * Creates new form JCustom_Base_Shot
     */
    public JCustom_Base_Shot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JCustom_Base_Shot.class, "JCustom_Base_Shot.jLabel1.text")); // NOI18N
        add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jToggleButton1, org.openide.util.NbBundle.getMessage(JCustom_Base_Shot.class, "JCustom_Base_Shot.jToggleButton1.text")); // NOI18N
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jToggleButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        add(jToggleButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jToggleButton1StateChanged

    private void jToggleButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton1ItemStateChanged
        System.out.println("Cambio \n"+evt.getStateChange()+this.jToggleButton1.isSelected()+" ##");
        if(this.isForward){
            this.jPhant_view.drawForwardBS=!this.jPhant_view.drawForwardBS;
        }else
        {
            this.jPhant_view.drawReverseBS=!this.jPhant_view.drawReverseBS;
        }
        this.jPhant_view.invalidate();
        this.jPhant_view.repaint();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    public void setPhntViewer(JPhantoming_view phant_view) {
       jPhant_view = phant_view;
        //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public boolean isForward;

    
}
