/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.smartUI;

import it.vs30.smartRefract.utils.Bool;
import it.vs30.myeditor.FineTuning;
import it.vs30.myeditor.JPhantoming_view;

/**
 *
 * @author PC
 */
public class JCustom_layer_chooser extends javax.swing.JPanel {
    protected Bool is_visible;
    protected JPhantoming_view jPhant_view=null;
    
    /**
     * Creates new form JCustom_layer_chooser
     */
    
    
    public JCustom_layer_chooser() {
        initComponents();
    }
    
    public JCustom_layer_chooser(String name,JCustom_layer_chooser[] lista,int self_index,Bool is_visible)
    {
        initComponents();
        jLabel1.setText(name);
        this.lista=lista;
        this.self_index=self_index;
        this.is_visible=is_visible;
        this.jCheckBox1.setSelected(is_visible.getValue());
        
    }
    
    public JCustom_layer_chooser(String name,JCustom_layer_chooser[] lista,int self_index,Bool is_visible,JPhantoming_view phant_view)
    {
        initComponents();
        jLabel1.setText(name);
        this.lista=lista;
        this.self_index=self_index;
        this.is_visible=is_visible;
        this.jCheckBox1.setSelected(is_visible.getValue());
        this.jPhant_view=phant_view;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JCustom_layer_chooser.class, "JCustom_layer_chooser.jLabel1.text")); // NOI18N
        add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(JCustom_layer_chooser.class, "JCustom_layer_chooser.jCheckBox1.text")); // NOI18N
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        add(jCheckBox1);

        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(JCustom_layer_chooser.class, "JCustom_layer_chooser.jRadioButton1.text")); // NOI18N
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        add(jRadioButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        fine.edit=this.jRadioButton1.isSelected();
        fine.setLayer(self_index,this.jRadioButton1.isSelected());
        
        
        if(this.jRadioButton1.isSelected()){
           this.fine.addLayerEditable(this.self_index);
           for(int i=0;i<lista.length;i++){
               if(i!=self_index){
                   lista[i].jRadioButton1.setSelected(false);
                   fine.setLayer(self_index,this.jRadioButton1.isSelected());
        
               }
           } 
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        this.is_visible.setValue(jCheckBox1.isSelected());
        
        
        this.jPhant_view.invalidate();
        this.jPhant_view.repaint();
        
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
    JCustom_layer_chooser[] lista;
    int self_index;
    FineTuning fine=null;
    
    public void setFineTuning(FineTuning ft){
        fine=ft;
    }
    public void setPhntViewer(JPhantoming_view phant_view) {
        jPhant_view=phant_view; //To change body of generated methods, choose Tools | Templates.
    }
}
