/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.smartUI;

import it.vs30.smartRefract.utils.FB_set;
import javax.swing.SpinnerNumberModel;
import it.vs30.myeditor.JPhantoming_view;

/**
 *
 * @author PC
 */
public class JShiftFB extends javax.swing.JPanel {
    private final FB_set fbs;
    public JPhantoming_view jPhant_view;
    /**
     * Creates new form JShiftFB
     */
    public JShiftFB() {
        initComponents();
        fbs=null;
        jPhant_view=null;
    }

    public JShiftFB(FB_set argFbs,JPhantoming_view argjPhant_view){
        initComponents();
        
        this.jLabel1.setText(argFbs.xshot+" m");
        fbs=argFbs;
        if(fbs.dir<0) jLabel1.setText("R-"+jLabel1.getText());
        jPhant_view=argjPhant_view;
        jSpinner1.setModel(new SpinnerNumberModel(fbs.shift, -100, +100, 0.2));
        this.jCheckBox1.setSelected(argFbs.visible);
        this.jCheckBox2.setSelected(argFbs.used);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();

        setLayout(new java.awt.GridLayout(1, 0));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JShiftFB.class, "JShiftFB.jLabel1.text")); // NOI18N
        add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(JShiftFB.class, "JShiftFB.jCheckBox1.text")); // NOI18N
        jCheckBox1.setToolTipText(org.openide.util.NbBundle.getMessage(JShiftFB.class, "JShiftFB.jCheckBox1.toolTipText")); // NOI18N
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        add(jCheckBox1);

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox2, org.openide.util.NbBundle.getMessage(JShiftFB.class, "JShiftFB.jCheckBox2.text")); // NOI18N
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2);

        jSpinner1.setToolTipText(org.openide.util.NbBundle.getMessage(JShiftFB.class, "JShiftFB.jSpinner1.toolTipText")); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        add(jSpinner1);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        fbs.visible=jCheckBox1.isSelected();
        jPhant_view.repaint();
        jPhant_view.invalidate();
        
        
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        fbs.shift=(Double)jSpinner1.getValue();
        jPhant_view.invalidate();
        jPhant_view.repaint();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        
        fbs.used=jCheckBox2.isSelected();
        jPhant_view.repaint();
        jPhant_view.invalidate();
        
        
        
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
