/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.vs30.smartUI;

import it.vs30.geometryView.geometryViewerTopComponent;
import it.vs30.smartRefract.utils.dromoSelection;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Path2D;
import java.awt.image.BufferedImage;
import java.text.DecimalFormat;
import org.myorg.myapi.APIObject;
import org.myorg.myapi.DrawingAPI;
import org.myorg.myapi.FirstBrakeList;
import org.myorg.myapi.Indagine;
import org.myorg.myviewer.MyViewerTopComponent;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 *
 * @author PC
 */
public class JTX_view extends javax.swing.JPanel {

    private Indagine proj = null;
    private FirstBrakeList ArrFB = null;
    private DrawingAPI dAPI = null;
    private APIObject obj = null;
    private boolean is_white;
    int indi = 0, indj = 0;
    private double margUp = 0.07;
    public boolean andata = true, ritorno = true;
    public dromoSelection dromoSelected = new dromoSelection();
    private int xmax;
    private int nchanel;
    private geometryViewerTopComponent geomTC;

    /**
     * Creates new form JTX_view
     */
    public JTX_view() {
        initComponents();
        System.setProperty("sun.java2d.opengl", "True");
    }

    public JTX_view(FirstBrakeList arr, Indagine prj) {
        initComponents();
        //jPanel.setBackground(Color.BLACK);
        System.setProperty("sun.java2d.opengl", "True");
        proj = prj;
        ArrFB = arr;
        //fb=fiB;
    }

    public JTX_view(APIObject obj) {
        initComponents();
        dAPI = new DrawingAPI(obj.proj, obj);
        this.obj = obj;
        this.proj = obj.proj;
        ArrFB = obj.fb;
    }

    public void setProj(Indagine project) {
        this.proj = project;

    }

    public void setObj(APIObject p_obj) {
        this.obj = p_obj;
        this.proj = this.obj.proj;

    }

    @Override
    public void paintComponent(Graphics g) {

        xmax = this.getWidth();
        ArrFB = (FirstBrakeList) proj.stesa.get(0);
        nchanel = xmax / (ArrFB.fb.length + 1);

        super.paintComponent(g);
        is_white = obj.is_white;
        drawDr(g, this.getWidth(), this.getHeight(), false);

        //drawDr(g,this.getWidth(), this.getHeight());
        //disegnaSegnale(g);
        //disegnaPrimoA(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        Graphics g = this.getGraphics();
        BufferedImage im = (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

        Graphics offg = im.getGraphics();
        super.paintComponent(offg);
        // offg.setColor(Color.red);
        // offg.drawString(evt.getX() + " " + evt.getY(), 30, 30);

        drawDr(offg, this.getWidth(), this.getHeight(), false);
        drawSl(offg, evt.getX(), evt.getY());

        g.drawImage(im, 0, 0, this);


    }//GEN-LAST:event_formMouseMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        int ymax = this.getHeight();
        //   int xmax = this.getWidth();
        ArrFB = (FirstBrakeList) proj.stesa.get(0);
        //   int nchanel = xmax / ArrFB.fb.length;
        //    int ychn = (ymax - (5 * nchanel)) / nchanel;
        //     int xshf = nchanel;
        double max = 0.00001;
        for (int j = 0; j < proj.stesa.size(); j++) {
            FirstBrakeList fbl = proj.stesa.get(j);
            for (int i = 1; i < fbl.fb.length; i++) {
                if (max < fbl.fb[i].time) {
                    max = (int) fbl.fb[i].time;
                }
            }
        }
        double dist = 99999.9;
        int x = evt.getX();
        int y = evt.getY();
        double ystp = ((ymax - (2 * margUp * ymax)) / max);
        int fi = indi;
        int j = indj;
        int in = indi;
        FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(j);
        for (int i = 1; i < fbl.fb.length; i++) {
            int xx = (i * nchanel);
            int yy = ymax - (int) (fbl.fb[i].time * ystp);
            //        g.drawLine((i*nchanel)-5,ymax-(int)(fbl.fb[i].time*ystp),(i*nchanel)+5,ymax-(int)(fbl.fb[i].time*ystp));
            double dst = Math.sqrt((Math.pow(xx - x, 2)) + Math.pow(yy - y, 2));
            if (dist > dst) {
                dist = dst;
                fi = i;
                indj = j;

            }
        }

        /*   if (assStr == 1) {
         undo = ((FirstBrakeList) proj.stesa.get(indj)).strato1 + "";
         undo_n = assStr;
         } else if (assStr == 2) {
         undo = ((FirstBrakeList) proj.stesa.get(indj)).strato2 + "";
         undo_n = assStr;
         }*/

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:

        Graphics g = this.getGraphics();
        BufferedImage im = (BufferedImage) this.createImage(this.getWidth(), this.getHeight());

        Graphics offg = im.getGraphics();
        super.paintComponent(offg);
        offg.setColor(Color.GREEN);
        //      offg.drawString(evt.getX() + " " + evt.getY(), 50, 40);
        drawDrag(offg, evt.getX(), evt.getY());

        g.drawImage(im, 0, 0, this);


    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        int ymax = this.getHeight();
        //    int xmax = this.getWidth();
        ArrFB = proj.stesa.get(0);

        int xshf = nchanel;
        double max = 0.00001;
        for (int j = 0; j < proj.stesa.size(); j++) {
            FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(j);
            for (int i = 1; i < fbl.fb.length; i++) {
                if (max < fbl.fb[i].time) {
                    max = (int) fbl.fb[i].time;
                }
            }
        }
        double dist = 99999.9;
        int x = evt.getX();
        int y = evt.getY();
        double ystp = ((ymax - (2 * margUp * ymax)) / max);
        int fi = indi;
        int j = indj;
        int in = indi;
        FirstBrakeList fbl = proj.stesa.get(j);
        for (int i = 0; i < fbl.fb.length; i++) {
            int xx = (i * nchanel) + xshf;
            int yy = ymax - (int) (fbl.fb[i].time * ystp);
            //        g.drawLine((i*nchanel)-5,ymax-(int)(fbl.fb[i].time*ystp),(i*nchanel)+5,ymax-(int)(fbl.fb[i].time*ystp));
            double dst = Math.sqrt((Math.pow(xx - x, 2)) + Math.pow(yy - y, 2));
            if (dist > dst) {
                dist = dst;
                fi = i;
                indj = j;

            }
        }
        if (in > fi) {
            int fi2 = in;
            in = fi;
            fi = fi2;
        }
        for (int i = in; i <= fi; i++) {
            if (dromoSelected.selected != 0) {
                fbl.fb[i].layer = dromoSelected.selected;
            }
        }
        //      fbl.setLayer(in, fi, dromoSelected.selected);

        fbl.updateLayer(in, fi, dromoSelected.selected);

        computeDromo(indj);

        proj.writeDromo();

        /*   if (assStr == 1) {
         undo = ((FirstBrakeList) proj.stesa.get(indj)).strato1 + "";
         undo_n = assStr;
         } else if (assStr == 2) {
         undo = ((FirstBrakeList) proj.stesa.get(indj)).strato2 + "";
         undo_n = assStr;
         }*/
        if (dromoSelected.selected != 0) {
            fbl.fb[fi].layer = dromoSelected.selected;
        }

    }//GEN-LAST:event_formMouseReleased

    private void drawDrag(Graphics g, int x, int y) {
        int ymax = this.getHeight();
        //  int xmax = this.getWidth();

        ArrFB = (FirstBrakeList) proj.stesa.get(indj);
        int xshf = nchanel;
        //g.setColor(Color.yellow);

        /* if (is_white) {
         g.setColor(Color.magenta);
         } else {
         g.setColor(Color.ORANGE);
         }
         */
        double max = 0.00001;
        for (int j = 0; j < proj.stesa.size(); j++) {
            FirstBrakeList fbl = proj.stesa.get(j);
            for (int i = 0; i < fbl.fb.length; i++) {
                if (max < fbl.fb[i].time) {
                    max = (int) fbl.fb[i].time;
                }
            }
        }
        max = 1.05 * max;

        double dist = 99999.9;
        try {
            double ystp = ((ymax - (2 * margUp * ymax)) / max);
            int yshf = (int) (margUp * ymax);
            int fi = indi;
            int j = indj;
            int in = indi;
            FirstBrakeList fbl = proj.stesa.get(j);
            double scoppio = ((fbl.scoppio - fbl.spaz_in) / fbl.spaz);
            for (int i = 0; i < fbl.fb.length; i++) {
                int xx = (i * nchanel) + xshf;
                int yy = ymax - (int) (fbl.fb[i].time * ystp) - yshf;
                if (ArrFB.scoppio < ((i) * ArrFB.spaz) + ArrFB.spaz_in) {

                    this.drawTriang(g, (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                } else {
                    this.drawCircle(g, (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                }

                //g.drawLine((i * nchanel) - 5 + xshf, ymax - (int) (fbl.fb[i].time * ystp) - yshf, (i * nchanel) + 5 + xshf, ymax - (int) (fbl.fb[i].time * ystp) - yshf);
                double dst = Math.sqrt((Math.pow(xx - x, 2)) + Math.pow(yy - y, 2));
                if (dist > dst) {
                    dist = dst;
                    if ((i - scoppio) * (in - scoppio) >= 0) {
                        fi = i;
                    }
                    indj = j;

                }
            }
            double[][] data = FirstBrakeList.getList(fbl.fb, in, fi, ((fbl.scoppio - fbl.spaz_in) / fbl.spaz), fbl.scoppio);
            double[] result = FirstBrakeList.getOLSRegression(data);

            double b = result[1];  //1 / (fbl.varianza(in, fi) / fbl.covarianza(in, fi));
            double a = result[0]; //fbl.media(in, fi) - b * fbl.mediax(in, fi);
            /*       dlg_Sel.inizio = in;
             dlg_Sel.fine = fi;
             dlg_Sel.setProj(proj);
             dlg_Sel.setAB(a, b);
             dlg_Sel.setIndj(indj);
             dlg_Sel.update();*/
            fbl = (FirstBrakeList) proj.stesa.get(indj);
            int yy = ymax - (int) (fbl.fb[fi].time * ystp) - yshf;
            int xx = (fi * nchanel);
            g.setFont(new Font("Dialog", Font.PLAIN, (int) (14)));
            DecimalFormat df = new DecimalFormat("#.###");

            g.drawString("Velocità : " + df.format(1 / b) + " km/s", 30, 50);

            //    System.out.println("=Dragged "+fbl.fb[in].time+" "+(b * ((in) * fbl.spaz + fbl.spaz_in) + a)+" "+(ymax - (int) (fbl.fb[in].time * ystp))+" "+(ymax - (int) (b * ((in) * fbl.spaz + fbl.spaz_in) + a) * ystp));
            g.drawOval(xx - 15 + xshf, yy - 15, 30, 30);
            g.drawLine((in * nchanel) + xshf, ymax - (int) ((b * ((in) * fbl.spaz + fbl.spaz_in) + a) * ystp) - yshf, (fi * nchanel) + xshf, ymax - (int) ((b * ((fi) * fbl.spaz + fbl.spaz_in) + a) * ystp) - yshf);
            //      undo_j = indj;
            /*    if (assStr == 1) {
             // undo=((FirstBrakeList)proj.stesa.get(indj)).strato1+"";
             // undo_n=assStr;
             ((FirstBrakeList) proj.stesa.get(indj)).dromo[0].b = b;
             ((FirstBrakeList) proj.stesa.get(indj)).dromo[0].a = a;

             ((FirstBrakeList) proj.stesa.get(indj)).strato1 = in + "-" + fi;
             ((FirstBrakeList) proj.stesa.get(indj)).setLayer(in, fi, 1);
             System.out.println(undo + " " + ((FirstBrakeList) proj.stesa.get(indj)).strato1);

             } else if (assStr == 2) {
             // undo=((FirstBrakeList)proj.stesa.get(indj)).strato2+"";
             // undo_n=assStr;

             ((FirstBrakeList) proj.stesa.get(indj)).dromo[1].b = b;
             ((FirstBrakeList) proj.stesa.get(indj)).dromo[1].a = a;
             ((FirstBrakeList) proj.stesa.get(indj)).setLayer(in, fi, 2);

             ((FirstBrakeList) proj.stesa.get(indj)).strato2 = in + "-" + fi;
             }*/
        } catch (Exception e1) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void drawSl(Graphics g, int x, int y) {
        int ymax = this.getHeight();
//        int xmax = this.getWidth();
        ArrFB = proj.stesa.get(0);

        int xshf = nchanel;

        if (is_white) {
            g.setColor(Color.magenta);
        } else {
            g.setColor(Color.ORANGE);
        }
        //g.setColor(Color.yellow);
        double max = 0.00001;
        for (int j = 0; j < proj.stesa.size(); j++) {
            FirstBrakeList fbl = proj.stesa.get(j);
            for (int i = 0; i < fbl.fb.length; i++) {
                if (max < fbl.fb[i].time) {
                    max = (int) fbl.fb[i].time;
                }
            }
        }
        max = 1.05 * max;

        double dist = 99999.9;
        int ar = 0;
        double ystp = ((ymax - (2 * margUp * ymax)) / max);
        int yshf = (int) (margUp * ymax);
        for (int j = 0; j < proj.stesa.size(); j++) {
            FirstBrakeList fbl = proj.stesa.get(j);
            for (int i = 0; i < fbl.fb.length; i++) {
                if (fbl.fb[i].time > -0.1 && fbl.fb[i].enabled) {
                    int xx = (i * nchanel) + xshf;
                    int yy = ymax - (int) (fbl.fb[i].time * ystp) - yshf;
                    double dst = Math.sqrt((Math.pow(xx - x, 2)) + Math.pow(yy - y, 2));

                    if ((fbl.scoppio < (i * fbl.spaz) + fbl.spaz_in)) {
                        if (andata) {
                            if (dist > dst) {
                                dist = dst;
                                indi = i;
                                indj = j;
                                ar = 1;

                            }

                        }

                    } else if (ritorno) {
                        if (dist > dst) {
                            dist = dst;
                            indi = i;
                            indj = j;
                            ar = 2;
                        }
                    }
                }
            }
        }

        FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(indj);
        dAPI.indj = indj;
        TopComponent tc = WindowManager.getDefault().findTopComponent("MyViewerTopComponent");
        Lookup tcLookup = tc.getLookup();
        // ((MyViewerTopComponent) tc).gmview.setBackground(Color.black);
        ((MyViewerTopComponent) tc).gmview.setGeom(fbl.scoppio, fbl.spaz, fbl.spaz_in, fbl.fb.length);
        ((MyViewerTopComponent) tc).gmview.setIndSel(indj);
        ((MyViewerTopComponent) tc).gmview.repaint();
        ((MyViewerTopComponent) tc).gmview.invalidate();

        tc = WindowManager.getDefault().findTopComponent("geometryViewerTopComponent");
        geomTC = (geometryViewerTopComponent) tc;
        geomTC.gmview.setGeom(fbl.scoppio, fbl.spaz, fbl.spaz_in, fbl.fb.length);
        geomTC.gmview.setIndSel(indj);
        geomTC.gmview.repaint();
        geomTC.gmview.invalidate();

        int yy = (ymax - (int) (fbl.fb[indi].time * ystp) - yshf);
        int xx = (indi * nchanel);
        // g.drawString(dist + " " + xx + " " + yy, 30, 50);
        g.drawOval(xx - 15 + xshf, yy - 15, 30, 30);
        proj.setFb(indj);
        ArrFB = proj.getFb();

        FontMetrics fontMetrics = g.getFontMetrics();
        int fontw = 0;

        if (ar == 1) {
            if (fbl.dromo[0].b != -999) {
                g.setColor(new Color(0.2f, 0.9f, 0.2f));
                g.drawString("" + (int) (1 / fbl.dromo[0].b * 1000) + " m/s ", xshf, ymax - (int) (0.45 * margUp * ymax));
                fontw += fontMetrics.stringWidth((int) (1 / fbl.dromo[0].b * 1000) + " km/s ") + 5;

            }
            if (fbl.dromo[1].b != -999) {
                g.setColor(new Color(0.6f, 0.9f, 0.9f));
                g.drawString("" + (int) (1 / fbl.dromo[1].b * 1000) + " m/s ", xshf + fontw, ymax - (int) (0.45 * margUp * ymax));
                fontw += fontMetrics.stringWidth((int) (1 / fbl.dromo[1].b * 1000) + " km/s ") + 5;
            }
            if (fbl.dromo[2].b != -999) {
                g.setColor(new Color(0.9f, 0.8f, 0.5f));
                g.drawString("" + (int) (1 / fbl.dromo[2].b * 1000) + " m/s ", xshf + fontw, ymax - (int) (0.45 * margUp * ymax));
            }

        }

        if (ar == 2) {
            if (fbl.dromoR[0].b != -999) {
                g.setColor(new Color(0.2f, 0.9f, 0.2f));
                g.drawString("" + (int) (1 / fbl.dromoR[0].b * 1000) + " m/s ", xshf, ymax - (int) (0.45 * margUp * ymax));
                fontw += fontMetrics.stringWidth((int) (1 / fbl.dromoR[0].b * 1000) + " km/s ") + 5;

            }
            if (fbl.dromoR[1].b != -999) {
                g.setColor(new Color(0.6f, 0.9f, 0.9f));
                g.drawString("" + (int) (1 / fbl.dromoR[1].b * 1000) + " m/s ", xshf + fontw, ymax - (int) (0.45 * margUp * ymax));
                fontw += fontMetrics.stringWidth((int) (1 / fbl.dromoR[1].b * 1000) + " km/s ") + 5;
            }
            if (fbl.dromoR[2].b != -999) {
                g.setColor(new Color(0.9f, 0.8f, 0.5f));
                g.drawString("" + (int) (1 / fbl.dromoR[2].b * 1000) + " m/s ", xshf + fontw, ymax - (int) (0.45 * margUp * ymax));
            }

        }

        drawDr(g, this.getWidth(), this.getHeight(), false);

    }

    private void drawDr(Graphics g, int w, int h, boolean b) {

        ArrFB = proj.stesa.get(indj);
        int ymax = h;//this.getHeight();
        //   int xmax = w;

        //int ymax = this.getHeight();
        //int xmax = this.getWidth();
        int xshf = nchanel;
        if (obj.is_white) {
            this.setBackground(Color.white);
            g.setColor(Color.black);
        } else {
            this.setBackground(Color.black);

            g.setColor(Color.white);
        }

        g.drawLine((int) (xshf * 0.75), (int) ((margUp * ymax)), (int) (xshf * 0.75), (int) (ymax - (margUp * ymax)));
        g.drawLine(xmax - (int) (xshf * 0.75), (int) ((margUp * ymax)), xmax - (int) (xshf * 0.75), (int) (ymax - (margUp * ymax)));
        g.drawLine((int) (xshf * 0.75), (int) (ymax - (margUp * ymax)), xmax - (int) (xshf * 0.75), (int) (ymax - (margUp * ymax)));
        g.drawLine((int) (xshf * 0.75), (int) ((margUp * ymax)), xmax - (int) (xshf * 0.75), (int) ((margUp * ymax)));

        //int yshf = (int) (margUp * ymax);
        //ymax=ymax-(int)(2*margUp*ymax);
        double max = 0.00001;
        for (int j = 0; j < proj.stesa.size(); j++) {
            FirstBrakeList fbl = (FirstBrakeList) proj.stesa.get(j);
            for (int i = 0; i < fbl.fb.length; i++) {
                if (max < (fbl.fb[i].time)) {
                    max = (int) (fbl.fb[i].time);
                }
            }
        }
        max = 1.05 * max;
        drawdr(g, max, w, h);
        drawSelected(g, max, w, h);
        drawtick(g, max, w, h);

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void drawdr(Graphics g, double max, int w, int h) {
        int ymax = h;
        // int l_xmax = w;
        ArrFB = proj.stesa.get(indj);
        //   int nchanel = xmax / (ArrFB.fb.length + 1);
        //    int ychn = (ymax - (5 * nchanel)) / nchanel;
        int xshf = nchanel;
        //    int in0 = 0, fi0 = 0, in1 = 0, fi1 = 0;
        int yshf = (int) (margUp * ymax);
        double ystp = ((ymax - ((2 * margUp) * ymax)) / max);

        for (int j = 0; j < proj.stesa.size(); j++) {

            ArrFB = (FirstBrakeList) proj.stesa.get(j);

//  /*
            Graphics2D g2 = (Graphics2D) g;
            g2.setStroke(new BasicStroke(1));
            Path2D p = new Path2D.Double();
            //p.moveTo((0 * nchanel) + xshf, ymax - (int) (ArrFB.fb[0].time * ystp) - yshf);
            boolean first = true;
            int layer = ArrFB.fb[0].layer;
            for (int i = 0; i < ArrFB.fb.length; i++) {
                if (ArrFB.fb[i].time > -0.1 && ArrFB.fb[i].enabled) {
                    if (ArrFB.scoppio < ((i) * ArrFB.spaz) + ArrFB.spaz_in) {
                        //System.out.println("@ G"+i+" spaz "+(((i-1)*ArrFB.spaz)+ArrFB.spaz_in)+" in "+ArrFB.spaz_in+" scop "+ArrFB.scoppio);
                        //setForeground(Color.GREEN);
                        switch (layer) {
                            case 3:
                                g2.setColor(Color.RED);
                                break;
                            case 2:
                                g2.setColor(Color.CYAN);
                                break;
                            case 1:
                                g2.setColor(Color.GREEN);
                                break;

                            default:
                                g2.setColor(Color.ORANGE);
                            //g2.setColor(Color.YELLOW);
                            }

                        if (andata) {
                            if (first) {
                                p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                                first = false;
                            }
                            // g2.setColor(Color.ORANGE);

                            if (layer == ArrFB.fb[i].layer) {
                                p.lineTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            } else {
                                //p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                                layer = ArrFB.fb[i].layer;
                                g2.draw(p);
                                p = new Path2D.Double();
                                p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                            }

                        }

                    } else {
                        //System.out.println("@ C"+i+" spaz "+(((i-1)*ArrFB.spaz)+ArrFB.spaz_in)+" in "+ArrFB.spaz_in+" scop "+ArrFB.scoppio);
                        //setForeground(Color.CYAN);

                        if (ritorno) {

                            if (first) {
                                p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                                first = false;
                            }
                            // g2.setColor(Color.ORANGE);

                            if (layer == ArrFB.fb[i].layer) {
                                p.lineTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            } else {
                                //p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                                layer = ArrFB.fb[i].layer;
                                g2.draw(p);
                                p = new Path2D.Double();
                                p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                            }

                            this.drawCircle(g, (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                        }
                    }

                    double is = (ArrFB.scoppio - ArrFB.spaz_in) / ArrFB.spaz;
                    try {

                        if (i < ArrFB.fb.length - 2) {
                            if (ArrFB.scoppio > (ArrFB.fb[i].posx) && ArrFB.scoppio < (ArrFB.fb[i + 1].posx)) {
                                p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                                p.lineTo((is * nchanel) + xshf, ymax - (int) (0 * ystp) - yshf);
                                p.lineTo(((i + 1) * nchanel) + xshf, ymax - (int) (ArrFB.fb[i + 1].time * ystp) - yshf);

                            }
                        } else {
                        }

                    } catch (Exception ex) {
                        System.err.println(ex.getMessage());
                    }

                    //g2.drawLine((i * nchanel) - 5+xshf, ymax - (int) (ArrFB.fb[i].time * ystp)-yshf, (i * nchanel) + 5+xshf, ymax - (int) (ArrFB.fb[i].time * ystp)-yshf);
                    //System.out.println(" @ "+i+" "+Double.toString(ArrFB.fb[i].time*4000)+" "+Double.toString(ymax-(int)(ArrFB.fb[i].time*ystp))+" "+ymax);
                    //g.drawLine(i*20-5,(int)((ArrFB.fb[i].time*20000/8000*(xmax-xshf))+xshf), (int)((ArrFB.fb[i].time*20000/8000*(xmax-xshf))+xshf), (ychn_max/2)+(ArrFB.fb[i].chan-1)*ychn_max-20);
                }
                switch (layer) {
                    case 3:
                        g2.setColor(Color.RED);
                        break;
                    case 2:
                        g2.setColor(Color.CYAN);
                        break;
                    case 1:
                        g2.setColor(Color.GREEN);
                        break;

                    default:
                    //g2.setColor(Color.YELLOW);
                }

                g2.draw(p);

            }

//*/
            FirstBrakeList fbl = proj.stesa.get(j);

            for (int i = 0; i < fbl.fb.length; i++) {
                if (ArrFB.fb[i].time > -0.1 && ArrFB.fb[i].enabled) {
                    if (fbl.scoppio < ((i) * fbl.spaz) + fbl.spaz_in) {

                        g.setColor(Color.DARK_GRAY);
                        if (andata) {
                            this.drawTriang(g, (i * nchanel) + xshf, ymax - (int) (fbl.fb[i].time * ystp) - yshf);
                        }

                    } else {

                        g.setColor(Color.LIGHT_GRAY);
                        if (ritorno) {
                            this.drawCircle(g, (i * nchanel) + xshf, ymax - (int) (fbl.fb[i].time * ystp) - yshf);
                        }
                    }

                    // g.drawLine((i * nchanel) - 5 + xshf, ymax - (int) (fbl.fb[i].time * ystp) - yshf, (i * nchanel) + 5 + xshf, ymax - (int) (fbl.fb[i].time * ystp) - yshf);
                }
                /*       if (andata) {
                 if (!fbl.strato1.equals("0-0")) {
                 String[] split = fbl.strato1.split("-");
                 in0 = Integer.parseInt(split[0]);
                 fi0 = Integer.parseInt(split[1]);

                 g.setColor(new Color(0.0f, 0.5f, 0.0f));

                 g.drawLine((in0 * nchanel) + xshf, ymax - (int) ((fbl.dromo[0].b * ((in0) * fbl.spaz + fbl.spaz_in) + fbl.dromo[0].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((fbl.dromo[0].b * ((fi0) * fbl.spaz + fbl.spaz_in) + fbl.dromo[0].a) * ystp) - yshf);

                 }
                 if (!fbl.strato2.equals("0-0")) {
                 String[] split = fbl.strato2.split("-");
                 in0 = Integer.parseInt(split[0]);
                 fi0 = Integer.parseInt(split[1]);
                 g.setColor(new Color(0.2f, 0.5f, 0.5f));
                 g.drawLine((in0 * nchanel) + xshf, ymax - (int) ((fbl.dromo[1].b * ((in0) * fbl.spaz + fbl.spaz_in) + fbl.dromo[1].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((fbl.dromo[1].b * ((fi0) * fbl.spaz + fbl.spaz_in) + fbl.dromo[1].a) * ystp) - yshf);
                 }
                 if (!fbl.strato3.equals("0-0")) {
                 String[] split = fbl.strato3.split("-");
                 in0 = Integer.parseInt(split[0]);
                 fi0 = Integer.parseInt(split[1]);
                 g.setColor(new Color(0.5f, 0.4f, 0.1f));
                 g.drawLine((in0 * nchanel) + xshf, ymax - (int) ((fbl.dromo[2].b * ((in0) * fbl.spaz + fbl.spaz_in) + fbl.dromo[2].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((fbl.dromo[2].b * ((fi0) * fbl.spaz + fbl.spaz_in) + fbl.dromo[2].a) * ystp) - yshf);
                 }
                 }
                 try {
                 if (ritorno) {

                 if (!fbl.strato1R.equals("0-0")) {
                 String[] split = fbl.strato1R.split("-");
                 in0 = Integer.parseInt(split[0]);
                 fi0 = Integer.parseInt(split[1]);
                 g.setColor(new Color(0.1f, 0.6f, 0.1f));
                 g.drawLine((in0 * nchanel) + xshf, ymax - (int) ((fbl.dromoR[0].b * ((in0) * fbl.spaz + fbl.spaz_in) + fbl.dromoR[0].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((fbl.dromoR[0].b * ((fi0) * fbl.spaz + fbl.spaz_in) + fbl.dromoR[0].a) * ystp) - yshf);
                 }
                 if (!fbl.strato2R.equals("0-0")) {
                 String[] split = fbl.strato2R.split("-");
                 in0 = Integer.parseInt(split[0]);
                 fi0 = Integer.parseInt(split[1]);
                 g.setColor(new Color(0.4f, 0.65f, 0.65f));
                 g.drawLine((in0 * nchanel) + xshf, ymax - (int) ((fbl.dromoR[1].b * ((in0) * fbl.spaz + fbl.spaz_in) + fbl.dromoR[1].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((fbl.dromoR[1].b * ((fi0) * fbl.spaz + fbl.spaz_in) + fbl.dromoR[1].a) * ystp) - yshf);
                 }

                 if (!fbl.strato3R.equals("0-0")) {
                 String[] split = fbl.strato3R.split("-");
                 in0 = Integer.parseInt(split[0]);
                 fi0 = Integer.parseInt(split[1]);
                 g.setColor(new Color(0.5f, 0.4f, 0.2f));
                 g.drawLine((in0 * nchanel) + xshf, ymax - (int) ((fbl.dromoR[2].b * ((in0) * fbl.spaz + fbl.spaz_in) + fbl.dromoR[2].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((fbl.dromoR[2].b * ((fi0) * fbl.spaz + fbl.spaz_in) + fbl.dromoR[2].a) * ystp) - yshf);
                 //System.out.println("Line "+(in0*nchanel)+" " +(ymax-(int)(fbl.dromo[2].b*((in0-1)*fbl.spaz+fbl.spaz_in)+fbl.dromo[2].a)*ystp)+" "+(fi0*nchanel)+" "+(ymax-(int) (fbl.dromo[2].b*((fi0-1)*fbl.spaz+fbl.spaz_in)+fbl.dromo[2].a)*ystp)+" "+fbl.strato3+" "+fbl.dromo[2].b+" "+fbl.dromo[2].a);
                 }
                 }
                 } catch (Exception e1) {
                 }
                 */
            }
        }
    }

    private void drawCircle(Graphics g, int x, int y) {

        g.drawOval(x - 4, y - 4, 8, 8);
    }

    private void drawtick(Graphics g, double max, int w, int h) {
        double ystp = 0.0;
        FirstBrakeList ArrFB = (FirstBrakeList) proj.stesa.get(0);
        int ymax = h;
        int xmax = w;
        int nchanel = xmax / (ArrFB.fb.length + 1);
        int ychn = (ymax - (0 * nchanel)) / nchanel;
        int xshf = nchanel;
        int majTic = 0, minTic = 0;
        Graphics2D g2 = (Graphics2D) g.create();

        ystp = (ymax - (2 * margUp * ymax)) / max;

        if (max / 10.0 < 1) {
            majTic = 2;
            minTic = 1;

        } else if (max / 10.0 < 2) {
            majTic = 3;
            minTic = 1;
        } else if (max / 10.0 < 4) {
            majTic = 5;
            minTic = 2;
        } else if (max / 10.0 < 10) {
            majTic = 10;
            minTic = 5;
        } else if (max / 10.0 < 30) {
            majTic = 20;
            minTic = 10;
        } else {
            majTic = (int) (max / 10);
            minTic = (int) (max / 20);
        }

        //g2.setColor(Color.white);
        if (obj.is_white) {
            g2.setColor(Color.black);
        } else {
            g2.setColor(Color.white);
        }
        //    if(this.m_print)g2.setColor(Color.BLACK);

        g2.setFont(new Font("Dialog", Font.PLAIN, (int) (12 * (w / 1000.0))));
        new Font("Dialog", Font.PLAIN, 12);

        FontMetrics fontMetrics = g2.getFontMetrics();

        int height = fontMetrics.getHeight();

        //FontMetrics fontMetrics = g2.getFontMetrics();
        //int height = fontMetrics.getHeight();
        for (int i = 0; i < max; i = i + minTic) {
            if (i % majTic == 0) {
                g2.drawLine((int) (xshf * 0.75), ymax - (int) (i * ystp + (margUp * ymax)), (int) (xshf * 0.6), ymax - (int) (i * ystp + (margUp * ymax)));
                int width = fontMetrics.stringWidth("" + (i));

                g2.drawString("" + (i), (int) (xshf * 0.55) - width, ymax - (int) (i * ystp + (margUp * ymax) - (height / 3)));
                g2.drawLine((int) (xmax - xshf * 0.75), ymax - (int) (i * ystp + (margUp * ymax)), (int) (xmax - xshf * 0.6), ymax - (int) (i * ystp + (margUp * ymax)));

            } else {
                g2.drawLine((int) (xshf * 0.75), ymax - (int) (i * ystp + (margUp * ymax)), (int) (xshf * 0.65), ymax - (int) (i * ystp + (margUp * ymax)));
                g2.drawLine((int) (xmax - xshf * 0.75), ymax - (int) (i * ystp + (margUp * ymax)), (int) (xmax - xshf * 0.65), ymax - (int) (i * ystp + (margUp * ymax)));
            }
        }

        for (int i = 0; i < ArrFB.fb.length; i++) {

            g2.drawLine((int) (xshf + (nchanel * i)), (int) ((margUp * ymax)), (int) (xshf + (nchanel * i)), (int) ((margUp * ymax) * 0.85));
            int width = fontMetrics.stringWidth("" + String.format("%.2f", (i * ArrFB.spaz + ArrFB.spaz_in)));

            g2.drawString("" + String.format("%.2f", i * ArrFB.spaz + ArrFB.spaz_in), (xshf + (nchanel * i) - (width / 2)), (int) ((margUp * ymax) * 0.83));
        }

    }

    private void drawTriang(Graphics g, int x, int y) {

        g.drawLine(x - 4, y - 4, x + 4, y - 4);
        g.drawLine(x - 4, y - 4, x, y + 4);
        g.drawLine(x + 4, y - 4, x, y + 4);

    }

    private void drawSelected(Graphics g, double max, int w, int h) {

        int ymax = h;
        //   int xmax = w;
        ArrFB = proj.stesa.get(indj);
        int xshf = nchanel;
        int in0 = 0, fi0 = 0, in1 = 0, fi1 = 0;
        int yshf = (int) (margUp * ymax);
        double ystp = ((ymax - ((2 * margUp) * ymax)) / max);

        ArrFB = (FirstBrakeList) proj.stesa.get(indj);
        //int ystp = (int) ((ymax - (2 * margUp * ymax)) / max);
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2));
        Path2D p = new Path2D.Double();
        p.moveTo((0 * nchanel) + xshf, ymax - (int) (ArrFB.fb[0].time * ystp) - yshf);
        int layer = ArrFB.fb[0].layer;
        boolean first = true;
        boolean print = false;
        if (!print) {
            for (int i = 0; i < ArrFB.fb.length; i++) {
                if (ArrFB.fb[i].time > -0.1 && ArrFB.fb[i].enabled) {

                    if (andata && (ArrFB.scoppio < ((i) * ArrFB.spaz) + ArrFB.spaz_in)) {

                        if (first) {
                            p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            first = false;
                        }
                        if (layer == ArrFB.fb[i].layer) {
                            switch (layer) {
                                case 3:
                                    g2.setColor(Color.RED);
                                    break;
                                case 2:
                                    g2.setColor(Color.CYAN);
                                    break;
                                case 1:
                                    g2.setColor(Color.GREEN);
                                    break;

                                default:
                                //g2.setColor(Color.YELLOW);
                            }
                            p.lineTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            g2.draw(p);
                            p = new Path2D.Double();
                            p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                        } else {
                            g2.setColor(Color.GRAY);
                            p.lineTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            layer = ArrFB.fb[i].layer;
                            g2.draw(p);
                            p = new Path2D.Double();
                            p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                        }
                    }
                    if (ritorno && !(ArrFB.scoppio < ((i) * ArrFB.spaz) + ArrFB.spaz_in)) {

                        if (first) {
                            p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            first = false;
                        }
                        if (layer == ArrFB.fb[i].layer) {
                            switch (layer) {
                                case 3:
                                    g2.setColor(Color.RED);
                                    break;
                                case 2:
                                    g2.setColor(Color.CYAN);
                                    break;
                                case 1:
                                    g2.setColor(Color.GREEN);
                                    break;

                                default:
                                //g2.setColor(Color.YELLOW);
                            }
                            p.lineTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            g2.draw(p);
                            p = new Path2D.Double();
                            p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                        } else {
                            g2.setColor(Color.GRAY);
                            p.lineTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                            layer = ArrFB.fb[i].layer;
                            g2.draw(p);
                            p = new Path2D.Double();
                            p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);

                        }
                    }

                    double is = (ArrFB.scoppio - ArrFB.spaz_in) / ArrFB.spaz;
                    try {

                        if (i < ArrFB.fb.length - 2) {
                            if (ArrFB.scoppio > (ArrFB.fb[i].posx) && ArrFB.scoppio < (ArrFB.fb[i + 1].posx)) {
                                p.moveTo((i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf);
                                p.lineTo((is * nchanel) + xshf, ymax - (int) (0 * ystp) - yshf);
                                p.lineTo(((i + 1) * nchanel) + xshf, ymax - (int) (ArrFB.fb[i + 1].time * ystp) - yshf);

                            }
                        } else {
                        }

                    } catch (Exception ex) {
                        System.err.println(ex.getMessage());
                    }

                    switch (layer) {
                        case 3:
                            g2.setColor(Color.RED);
                            break;
                        case 2:
                            g2.setColor(Color.CYAN);
                            break;
                        case 1:
                            g2.setColor(Color.GREEN);
                            break;

                        default:
                        //g2.setColor(Color.YELLOW);
                    }

                    g2.draw(p);
                    //          in0 = 0;
                    //          fi0 = 0;
                    g2 = (Graphics2D) g;
                    g2.setStroke(new BasicStroke(3));

                    try {

                        if (andata) {
                            if (!ArrFB.strato1.equals("0-0")) {
                                String[] split = ArrFB.strato1.split("-");
                                in0 = Integer.parseInt(split[0]);
                                fi0 = Integer.parseInt(split[1]);
                                g2.setColor(new Color(0.2f, 0.9f, 0.2f));
                                //                  g2.drawLine((in0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromo[0].b * ((in0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromo[0].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromo[0].b * ((fi0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromo[0].a) * ystp) - yshf);
                            }
                            if (!ArrFB.strato2.equals("0-0")) {
                                String[] split = ArrFB.strato2.split("-");
                                in0 = Integer.parseInt(split[0]);
                                fi0 = Integer.parseInt(split[1]);
                                g2.setColor(new Color(0.6f, 0.9f, 0.9f));

                                //                  g2.drawLine((in0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromo[1].b * ((in0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromo[1].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromo[1].b * ((fi0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromo[1].a) * ystp) - yshf);
                            }

                            if (!ArrFB.strato3.equals("0-0")) {
                                String[] split = ArrFB.strato3.split("-");
                                in0 = Integer.parseInt(split[0]);
                                fi0 = Integer.parseInt(split[1]);
                                g2.setColor(new Color(0.9f, 0.8f, 0.5f));
                                //                  g2.drawLine((in0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromo[2].b * ((in0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromo[2].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromo[2].b * ((fi0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromo[2].a) * ystp) - yshf);
                                //System.out.println("Line "+(in0*nchanel)+" " +(ymax-(int)(ArrFB.dromo[2].b*((in0-1)*ArrFB.spaz+ArrFB.spaz_in)+ArrFB.dromo[2].a)*ystp)+" "+(fi0*nchanel)+" "+(ymax-(int) (ArrFB.dromo[2].b*((fi0-1)*ArrFB.spaz+ArrFB.spaz_in)+ArrFB.dromo[2].a)*ystp)+" "+ArrFB.strato3+" "+ArrFB.dromo[2].b+" "+ArrFB.dromo[2].a);
                            }
                        }
                    } catch (Exception e1) {
                    }

                    try {
                        if (ritorno) {

                            if (!ArrFB.strato1R.equals("0-0")) {
                                String[] split = ArrFB.strato1R.split("-");
                                in0 = Integer.parseInt(split[0]);
                                fi0 = Integer.parseInt(split[1]);
                                g2.setColor(new Color(0.3f, 0.9f, 0.2f));
                                //                 g2.drawLine((in0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromoR[0].b * ((in0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromoR[0].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromoR[0].b * ((fi0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromoR[0].a) * ystp) - yshf);
                            }
                            if (!ArrFB.strato2R.equals("0-0")) {
                                String[] split = ArrFB.strato2R.split("-");
                                in0 = Integer.parseInt(split[0]);
                                fi0 = Integer.parseInt(split[1]);
                                g2.setColor(new Color(0.6f, 0.9f, 0.9f));
                                //                 g2.drawLine((in0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromoR[1].b * ((in0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromoR[1].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromoR[1].b * ((fi0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromoR[1].a) * ystp) - yshf);
                            }

                            if (!ArrFB.strato3R.equals("0-0")) {
                                String[] split = ArrFB.strato3R.split("-");
                                in0 = Integer.parseInt(split[0]);
                                fi0 = Integer.parseInt(split[1]);
                                g2.setColor(new Color(0.9f, 0.8f, 0.5f));
                                //                 g2.drawLine((in0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromoR[2].b * ((in0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromoR[2].a) * ystp) - yshf, (fi0 * nchanel) + xshf, ymax - (int) ((ArrFB.dromoR[2].b * ((fi0) * ArrFB.spaz + ArrFB.spaz_in) + ArrFB.dromoR[2].a) * ystp) - yshf);
                                //System.out.println("Line "+(in0*nchanel)+" " +(ymax-(int)(ArrFB.dromo[2].b*((in0-1)*ArrFB.spaz+ArrFB.spaz_in)+ArrFB.dromo[2].a)*ystp)+" "+(fi0*nchanel)+" "+(ymax-(int) (ArrFB.dromo[2].b*((fi0-1)*ArrFB.spaz+ArrFB.spaz_in)+ArrFB.dromo[2].a)*ystp)+" "+ArrFB.strato3+" "+ArrFB.dromo[2].b+" "+ArrFB.dromo[2].a);
                            }
                        }

                    } catch (Exception e1) {
                    }
                }
            }
            drawRette(g, max, w, h);
        }

        //To change body of generated methods, choose Tools | Templates.
    }

    private void computeDromo(int index_dromo) {
        //for (int j = 0; j < proj.stesa.size(); j++) {
        FirstBrakeList fbl = proj.stesa.get(index_dromo);
        //FirstBrakeList.getList(fbl.fb, 1, 1);
        for (int i = 1; i <= 3; i++) {

            double[][] data = FirstBrakeList.getList(fbl, i, true, fbl.scoppio, fbl.spaz_in);
            if (data.length > 0) {
                double[] dromo = FirstBrakeList.getOLSRegression(data);
                fbl.dromo[i - 1].a = dromo[0];
                fbl.dromo[i - 1].b = dromo[1];
            } else {
                fbl.dromo[i - 1].a = -999;
                fbl.dromo[i - 1].b = -999;
            }
            data = FirstBrakeList.getList(fbl, i, false, fbl.scoppio, fbl.spaz_in);
            if (data.length > 0) {
                double[] dromo = FirstBrakeList.getOLSRegression(data);
                fbl.dromoR[i - 1].a = dromo[0];
                fbl.dromoR[i - 1].b = dromo[1];
            } else {
                fbl.dromoR[i - 1].a = -999;
                fbl.dromoR[i - 1].b = -999;
            }

        }
        //}
    }
    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    private void drawRette(Graphics g, double max, int w, int h) {
        int ymax = h;
        // int xmax = w;
        ArrFB = (FirstBrakeList) proj.stesa.get(indj);
        // int nchanel = xmax / (ArrFB.fb.length + 2);
        int ychn = (ymax - (5 * nchanel)) / nchanel;
        int xshf = nchanel;
        int in0 = 0, fi0 = 0, in1 = 0, fi1 = 0;
        int yshf = (int) (margUp * ymax);
        double ystp = ((ymax - ((2 * margUp) * ymax)) / max);

        ArrFB = proj.stesa.get(indj);
        //int ystp = (int) ((ymax - (2 * margUp * ymax)) / max);
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2));
        Path2D p = new Path2D.Double();

        if (andata) {
            if (ArrFB.dromo[0].b != -999) {
                double x = 0;
                if (ArrFB.dromo[1].b != -999) {
                    x = (ArrFB.dromo[0].intersection(ArrFB.dromo[1])[0]);
                } else {
                    x = obj.find_last_X(ArrFB, 1, andata);
                }

                double y = ArrFB.dromo[0].time(x);
                x = (x - ArrFB.spaz_in) / ArrFB.spaz;
                // (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf

                double x0 = (ArrFB.scoppio - ArrFB.spaz_in) / ArrFB.spaz;
                g2.setColor(Color.GREEN);
                g2.drawOval((int) ((x * nchanel) + xshf) - 2, ymax - (int) (y * ystp) - yshf - 2, 4, 4);
                g2.drawLine((int) ((x0 * nchanel) + xshf), ymax - (int) (0.0 * ystp) - yshf, (int) ((x * nchanel) + xshf), ymax - (int) (y * ystp) - yshf);
            }
            if (ArrFB.dromo[1].b != -999) {
                int layer = 2;
                double x0 = 0;
                if (ArrFB.dromo[0].b != -999) {
                    x0 = (ArrFB.dromo[1].intersection(ArrFB.dromo[0])[0]);
                } else {
                    x0 = this.obj.find_first_X(ArrFB, layer, true);
                }
                double y0 = ArrFB.dromo[1].time(x0);
                double x1 = 0;
                if (ArrFB.dromo[2].b != -999) {
                    x1 = (ArrFB.dromo[1].intersection(ArrFB.dromo[2])[0]);
                } else {
                    x1 = this.obj.find_last_X(ArrFB, layer, true);

                }
                double y1 = ArrFB.dromo[1].time(x1);
                x0 = (x0 - ArrFB.spaz_in) / ArrFB.spaz;
                x1 = (x1 - ArrFB.spaz_in) / ArrFB.spaz;
                // (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf
                //double x0=(ArrFB.scoppio-ArrFB.spaz_in)/ArrFB.spaz;
                g2.setColor(Color.CYAN);
                g2.drawOval((int) ((x1 * nchanel) + xshf) - 2, ymax - (int) (y1 * ystp) - yshf - 2, 4, 4);
                g2.drawLine((int) ((x0 * nchanel) + xshf), ymax - (int) (y0 * ystp) - yshf, (int) ((x1 * nchanel) + xshf), ymax - (int) (y1 * ystp) - yshf);
            }
            if (ArrFB.dromo[2].b != -999) {
                int layer = 3;
                double x0 = 0;
                if (ArrFB.dromo[2].b != -999 && ArrFB.dromo[1].b != -999) {

                    x0 = (ArrFB.dromo[2].intersection(ArrFB.dromo[1])[0]);
                } else {
                    x0 = this.obj.find_first_X(ArrFB, layer, true);
                }
                double y0 = ArrFB.dromo[2].time(x0);
                double x1 = 0;

                x1 = this.obj.find_last_X(ArrFB, layer, true);

                double y1 = ArrFB.dromo[2].time(x1);
                x0 = (x0 - ArrFB.spaz_in) / ArrFB.spaz;
                x1 = (x1 - ArrFB.spaz_in) / ArrFB.spaz;
                // (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf
                //double x0=(ArrFB.scoppio-ArrFB.spaz_in)/ArrFB.spaz;
                g2.setColor(Color.ORANGE);
                g2.drawOval((int) ((x1 * nchanel) + xshf) - 2, ymax - (int) (y1 * ystp) - yshf - 2, 4, 4);
                g2.drawLine((int) ((x0 * nchanel) + xshf), ymax - (int) (y0 * ystp) - yshf, (int) ((x1 * nchanel) + xshf), ymax - (int) (y1 * ystp) - yshf);
            }

        }
        if (ritorno) {
            if (ArrFB.dromoR[0].b != -999) {
                double x = 0;
                if (ArrFB.dromoR[1].b != -999) {
                    x = (ArrFB.dromoR[0].intersection(ArrFB.dromoR[1])[0]);
                } else {
                    x = obj.find_last_X(ArrFB, 1, false);
                }

                double y = ArrFB.dromoR[0].time(x);
                x = (x - ArrFB.spaz_in) / ArrFB.spaz;
                // (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf
                double x0 = (ArrFB.scoppio - ArrFB.spaz_in) / ArrFB.spaz;
                g2.setColor(Color.GREEN);
                g2.drawOval((int) ((x * nchanel) + xshf) - 2, ymax - (int) (y * ystp) - yshf - 2, 4, 4);
                g2.drawLine((int) ((x0 * nchanel) + xshf), ymax - (int) (0.0 * ystp) - yshf, (int) ((x * nchanel) + xshf), ymax - (int) (y * ystp) - yshf);
            }
            if (ArrFB.dromoR[1].b != -999) {
                int layer = 2;
                double x0 = 0;
                if (ArrFB.dromoR[0].b != -999) {
                    x0 = (ArrFB.dromoR[1].intersection(ArrFB.dromoR[0])[0]);
                } else {
                    x0 = this.obj.find_first_X(ArrFB, layer, false);
                }
                double y0 = ArrFB.dromoR[1].time(x0);
                double x1 = 0;
                if (ArrFB.dromoR[2].b != -999) {
                    x1 = (ArrFB.dromoR[1].intersection(ArrFB.dromoR[2])[0]);
                } else {
                    x1 = this.obj.find_last_X(ArrFB, layer, false);

                }
                double y1 = ArrFB.dromoR[1].time(x1);
                x0 = (x0 - ArrFB.spaz_in) / ArrFB.spaz;
                x1 = (x1 - ArrFB.spaz_in) / ArrFB.spaz;
                // (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf
                //double x0=(ArrFB.scoppio-ArrFB.spaz_in)/ArrFB.spaz;
                g2.setColor(Color.CYAN);
                g2.drawOval((int) ((x1 * nchanel) + xshf) - 2, ymax - (int) (y1 * ystp) - yshf - 2, 4, 4);
                g2.drawLine((int) ((x0 * nchanel) + xshf), ymax - (int) (y0 * ystp) - yshf, (int) ((x1 * nchanel) + xshf), ymax - (int) (y1 * ystp) - yshf);
            }
            if (ArrFB.dromoR[2].b != -999) {
                int layer = 3;
                double x0 = 0;
                if (ArrFB.dromoR[1].b != -999) {
                    x0 = (ArrFB.dromoR[2].intersection(ArrFB.dromoR[1])[0]);
                } else {
                    x0 = this.obj.find_first_X(ArrFB, layer, false);
                }
                double y0 = ArrFB.dromoR[2].time(x0);
                double x1 = 0;

                x1 = this.obj.find_last_X(ArrFB, layer, false);

                double y1 = ArrFB.dromoR[2].time(x1);
                x0 = (x0 - ArrFB.spaz_in) / ArrFB.spaz;
                x1 = (x1 - ArrFB.spaz_in) / ArrFB.spaz;
                // (i * nchanel) + xshf, ymax - (int) (ArrFB.fb[i].time * ystp) - yshf
                //double x0=(ArrFB.scoppio-ArrFB.spaz_in)/ArrFB.spaz;
                g2.setColor(Color.ORANGE);
                g2.drawOval((int) ((x1 * nchanel) + xshf) - 2, ymax - (int) (y1 * ystp) - yshf - 2, 4, 4);
                g2.drawLine((int) ((x0 * nchanel) + xshf), ymax - (int) (y0 * ystp) - yshf, (int) ((x1 * nchanel) + xshf), ymax - (int) (y1 * ystp) - yshf);
            }

        }

        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
