/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * geomView.java
 *
 * Created on 22-apr-2011, 17.29.18
 */
package it.vs30.geometryView;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import org.myorg.myapi.FirstBrakeList;
//import org.myorg.myapi.APIObject;

/**
 *
 * @author user
 */
public class geomView1 extends javax.swing.JPanel {

    /**
     * Creates new form geomView
     */
    public geomView1() {
        initComponents();
    }

    void DrawOneShot(Graphics g) {
        super.paintComponent(g);
        if (!is_white) {
            this.setBackground(Color.black);
        } else {
            this.setBackground(Color.white);
        }
        try {
            g.setColor(Color.red);
            //  g.drawString(" "+shot+" "+spaz_in+" "+spaz+" "+nchan, 10, 20);

            double min = 0;
            if (shot < spaz_in) {
                min = shot;
            } else {
                min = spaz_in;
            }
            double max = 0;
            if (shot > spaz_in + ((nchan - 1) * spaz)) {
                max = shot;
            } else {
                max = spaz_in + ((nchan - 1) * spaz);
            }

            double dim = max - min;
            double step = (this.getWidth() - (this.getWidth() * 0.1)) / dim;

            double shift = (this.getWidth() * 0.1) / 2;

            //   g.drawLine((int)((shot-min)*step+shift), 20, (int)((shot-min)*step+shift), 40);
            drawShot(g, (int) ((shot - min) * step + shift), 20);
            g.setColor(Color.GRAY);
            g.drawLine(0, 30, this.getWidth(), 30);

            if (!is_white) {
                g.setColor(Color.CYAN);

            } else {
                g.setColor(Color.darkGray);
            }

            for (int i = 0; i < nchan; i++) {
                //g.drawLine((int)((spaz_in+(spaz*i)-min)*step+shift), 20, (int)((spaz_in+(spaz*i)-min)*step+shift), 40);
                drawGeo(g, (int) ((spaz_in + (spaz * i) - min) * step + shift), 20);
            }

        } catch (Exception ex) {
            System.out.println("Errore disegno geometria");
        }
    }

    @Override
    public void paintComponent(Graphics g) {

        switch (vis) {
            case 0:
                this.DrawOneShot(g);
                break;
            case 1:
                this.DrawStesaCompleta(g);
                break;
            default:
                break;

        }

    }

    int nchan = 0;
    public int vis = 0;
    double shot = 0, spaz = 0, spaz_in = 0;

    public void drawGeo(Graphics g, int x, int y) {
        g.drawLine(x - 5, y, x + 5, y);
        g.drawLine(x - 5, y, x, y + 10);
        g.drawLine(x + 5, y, x, y + 10);
        g.drawLine(x, y + 10, x, y + 20);
    }

    public void drawShot(Graphics g, int x, int y) {
        g.drawRect(x - 5, y + 5, 10, 5);
        //g.drawLine(x-5,y+5,x+5,y+5);
        g.drawLine(x - 5, y + 5, x + 5, y + 10);
        g.drawLine(x + 5, y + 5, x - 5, y + 10);
        g.drawLine(x, y + 10, x, y + 20);
    }

    public void setGeom(double shot, double spaz, double spaz_in, int nchan) {
        this.shot = shot;
        this.spaz = spaz;
        this.spaz_in = spaz_in;
        this.nchan = nchan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean is_white = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public double[] shotA;

    public void setStesa(ArrayList stesa) {
        try {
            FirstBrakeList fbl =null; // (FirstBrakeList) stesa.get(0);
            shotA = new double[stesa.size()];
            for (int i = 0; i < stesa.size(); i++) {
                fbl = (FirstBrakeList) stesa.get(i);
                shotA[i] = fbl.scoppio;
            }
        } catch (Exception ex) {
            System.out.println("Eccezione in setStesa() @ geomView"+ex.getMessage());
        }

    }

    public void DrawStesaCompleta(Graphics g) {

        super.paintComponent(g);
        boolean is_white = false;
        if (!is_white) {
            this.setBackground(Color.black);
        } else {
            this.setBackground(Color.white);
        }
        try {
            //g.setColor(Color.red);
            //  g.drawString(" "+shot+" "+spaz_in+" "+spaz+" "+nchan, 10, 20);

            double min = 999;
            double max = 0;

            for (int i = 0; i < shotA.length; i++) {

                if (shotA[i] < spaz_in) {
                    if (shotA[i] < min) {
                        min = shotA[i];
                    }
                } else {
                    if (spaz_in < min) {
                        min = spaz_in;
                    }
                }

                if (shotA[i] > spaz_in
                        + ((nchan
                        - 1) * spaz) && shotA[i] > max) {
                    max = shotA[i];
                } else if (max<spaz_in + ((nchan - 1) * spaz)){
                    max = spaz_in + ((nchan - 1) * spaz);
                }
            }
            double dim = max - min;
            double step = (this.getWidth() - (this.getWidth() * 0.1)) / dim;

            double shift = (this.getWidth() * 0.1) / 2;

            //   g.drawLine((int)((shot-min)*step+shift), 20, (int)((shot-min)*step+shift), 40);
            for (int i = 0; i < shotA.length; i++) {
                if (i == this.indj) {
                    g.setColor(Color.orange);
                } else {
                    g.setColor(Color.red);
                }

                drawShot(g, (int) ((shotA[i] - min) * step + shift), 20);
            }
            g.setColor(Color.GRAY);
            g.drawLine(0, 30, this.getWidth(), 30);

            if (!is_white) {
                g.setColor(Color.CYAN);

            } else {
                g.setColor(Color.darkGray);
            }

            for (int i = 0; i < nchan; i++) {
                //g.drawLine((int)((spaz_in+(spaz*i)-min)*step+shift), 20, (int)((spaz_in+(spaz*i)-min)*step+shift), 40);
                drawGeo(g, (int) ((spaz_in + (spaz * i) - min) * step + shift), 20);
            }

        } catch (Exception ex) {
        }

    }
    //  int nchan = 0;
    //  double shot[], spaz = 0, spaz_in = 0;

    public void setGeom(double[] shot, double spaz, double spaz_in, int nchan) {
        //    this.shot = shot;
        this.spaz = spaz;
        this.spaz_in = spaz_in;
        this.nchan = nchan;
    }
    private int indj;

    public void setIndSel(int indj) {

        this.indj = indj;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
